diff -Nuar dxflib-2.2.0.0-1.src-old/Makefile.in dxflib-2.2.0.0-1.src/Makefile.in
--- dxflib-2.2.0.0-1.src-old/Makefile.in	2010-09-23 16:16:09.304526874 +0300
+++ dxflib-2.2.0.0-1.src/Makefile.in	2010-09-23 16:19:14.817152742 +0300
@@ -24,6 +24,10 @@
 #
 SHELL = /bin/sh
 
+VERSION      = 2
+SHAREDNAME   = libdxflib.so
+SONAME       = $(SHAREDNAME).$(VERSION)
+
 CC           = @CC@
 CXX          = @CXX@
 CFLAGS       = -I./src @CFLAGS@ @DEFS@
@@ -33,6 +37,7 @@
 MAKEDEPEND   = @MAKEDEPEND@
 AR           = ar
 ARFLAGS      = -rs
+SHAREDFLAGS  = -shared -Wl,-soname,$(SONAME)
 
 BASE_DIR = ./src
 
@@ -58,22 +63,26 @@
 INS =  $(BASE_INS)
 
 .cpp.o:  
-	$(CXX) $(CFLAGS) -c $< -o $@
-
+	$(CXX) $(CXXFLAGS) -fPIC -c $< -o $@
 
-all: ./lib/libdxflib.a
+all: ./lib/$(SONAME)
 
 ./lib/libdxflib.a: $(OBJ) 
 	test -d ./lib || mkdir ./lib
 	$(AR) $(ARFLAGS) ./lib/libdxflib.a $(OBJ)
 
-install: ./lib/libdxflib.a
-	test -d $(LIBDIR) || mkdir -p $(LIBDIR)
-	test -d $(INCDIR) || mkdir -p $(INCDIR)
-	$(INSTALL_DATA) ./lib/libdxflib.a $(LIBDIR)
+./lib/$(SONAME): $(OBJ) 
+	test -d ./lib || mkdir ./lib
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(SHAREDFLAGS) -o ./lib/$(SONAME) $(OBJ)
+
+install: ./lib/$(SONAME)
+	test -d $(DESTDIR)$(LIBDIR) || mkdir -p $(DESTDIR)$(LIBDIR)
+	test -d $(DESTDIR)$(INCDIR) || mkdir -p $(DESTDIR)$(INCDIR)
+	$(INSTALL) ./lib/$(SONAME) $(DESTDIR)$(LIBDIR)
+	-(ln -s $(SONAME) $(DESTDIR)$(LIBDIR)/$(SHAREDNAME))
 	#-(ln -s $(LIBDIR)/libdxflib.a $(LIBDIR)/libdxflib.a)
 	for IFILE in $(INS); do \
-		$(INSTALL_DATA) $$IFILE  $(INCDIR); \
+		$(INSTALL_DATA) $$IFILE  $(DESTDIR)$(INCDIR); \
 	done
 
 clean:
