Index: fdupes-1.50-PR2/Makefile
===================================================================
--- fdupes-1.50-PR2.orig/Makefile
+++ fdupes-1.50-PR2/Makefile
@@ -11,7 +11,7 @@
 # determination of the actual installation directories.
 # Suggested values are "/usr/local", "/usr", "/pkgs/fdupes-$(VERSION)"
 #
-PREFIX = /usr/local
+PREFIX = /usr
 
 #
 # Certain platforms do not support long options (command line options).
@@ -50,7 +50,7 @@ BIN_DIR = $(PREFIX)/bin
 # MAN_DIR indicates directory where the fdupes man page is to be 
 # installed. Suggested value is "$(PREFIX)/man/man1"
 #
-MAN_BASE_DIR = $(PREFIX)/man
+MAN_BASE_DIR = $(PREFIX)/share/man
 MAN_DIR = $(MAN_BASE_DIR)/man1
 MAN_EXT = 1
 
@@ -72,9 +72,9 @@ MKDIR   = mkdir -p
 # Make Configuration
 #
 CC = gcc
-COMPILER_OPTIONS = -Wall -O -g
+COMPILER_OPTIONS = -Wall
 
-CFLAGS= $(COMPILER_OPTIONS) -I. -DVERSION=\"$(VERSION)\" $(EXTERNAL_MD5) $(EXPERIMENTAL_RBTREE) $(OMIT_GETOPT_LONG)
+CFLAGS += $(COMPILER_OPTIONS) -I. -DVERSION=\"$(VERSION)\" $(EXTERNAL_MD5) $(EXPERIMENTAL_RBTREE) $(OMIT_GETOPT_LONG)
 
 INSTALL_PROGRAM = $(INSTALL) -c -m 0755
 INSTALL_DATA    = $(INSTALL) -c -m 0644
@@ -94,7 +94,7 @@ OBJECT_FILES = fdupes.o md5/md5.o $(ADDI
 all: fdupes
 
 fdupes: $(OBJECT_FILES)
-	$(CC) $(CFLAGS) -o fdupes $(OBJECT_FILES)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o fdupes $(OBJECT_FILES)
 
 installdirs:
 	test -d $(BIN_DIR) || -$(MKDIR) $(BIN_DIR)
