Index: libdumbtts-0.3.2/src/Makefile
===================================================================
--- libdumbtts-0.3.2.orig/src/Makefile
+++ libdumbtts-0.3.2/src/Makefile
@@ -10,7 +10,6 @@ LIBTAG = $(LIB_VERSION).$(RELEASE)
 INSTALL = /usr/bin/install
 LN_SF = /bin/ln -sf
 MKDIR = mkdir -p
-C = gcc
 PIC =
 ARCH = $(shell uname -m)
 
@@ -25,10 +24,10 @@ all: $(LIB_NAME)
 	mv $(LIB_NAME) $(LIB_NAME).$(LIBTAG)
 
 $(OBJS): $(SRCS)
-	$(C) $(PIC) -o $(OBJS) -c -Wall libdumbtts.c
+	$(CC) $(CFLAGS) $(PIC) -o $(OBJS) -c libdumbtts.c
 
 $(LIB_NAME): $(OBJS)
-	$(C) $(PIC) -shared -Wl,-soname,$(LIB_NAME).$(LIB_VERSION) -o $@ $(OBJS)
+	$(CC) $(PIC) $(LDFLAGS) -shared -Wl,-soname,$(LIB_NAME).$(LIB_VERSION) -o $@ $(OBJS)
 
 clean:
 	rm -f *.o *.a *~ $(LIB_NAME).$(LIBTAG) ../conf/*~
