#!/bin/bash

MAIN="sauerbraten"
DATADIR="/usr/share/$MAIN"
TARGET="$HOME/.$MAIN"
TOSYMLINK="data packages bin_unix"
# TOCOPY="basicdat players import egoboo controls.txt setup.txt"

if [ ! -e "$TARGET" ]; then
	mkdir "$TARGET"
fi
for d in $TOSYMLINK; do
	if [ ! -e "$TARGET/$d" ] ; then
		ln -s "$DATADIR/$d" "$TARGET/$d"
	fi
done
#for f in $TOCOPY; do
#	if [ ! -e "$TARGET/$f" ] ; then
#		cp -R "$DATADIR/$f" "$TARGET/"
#	fi
#done

cd "$TARGET"
exec ./bin_unix/sauer_client "$@"

