Index: src/Makefile.in
===================================================================
--- src/Makefile.in.orig
+++ src/Makefile.in
@@ -257,8 +257,8 @@ target_vendor = @target_vendor@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 NULL = 
-gamesdir = $(prefix)/games
-scoredir = /var/games/tecnoballz
+gamesdir = $(prefix)/bin
+scoredir = /var/lib/games/tecnoballz
 score = tecnoballz.hi
 SUBDIRS = TecnoballZ 
 tecnoballz_SOURCES = $(SOURCES_MAIN) 
@@ -324,7 +324,7 @@ SOURCES_MAIN = \
   sprite_projectile.cc \
   sprite_ship.cc \
   sprite_wall.cc \
-  supervisor.c \
+  supervisor.cc \
   supervisor_bricks_level.cc \
   supervisor_main_menu.cc \
   supervisor_map_editor.cc \
