Index: ZynAddSubFX-2.4.3/src/Makefile
===================================================================
--- ZynAddSubFX-2.4.3.orig/src/Makefile
+++ ZynAddSubFX-2.4.3/src/Makefile
@@ -1,10 +1,6 @@
 include Makefile.inc
 
-ifneq ($(MAKECMDGOALS),debug)
-  CXXFLAGS= -O2 -Wall -g -fPIC
-else 
-  CXXFLAGS= -O2 -Wall -Wpointer-arith -fPIC
-endif
+CXXFLAGS+=
 
 CXXFLAGS += -DOS_$(OS_PORT) -D$(MIDIIN)MIDIIN -DFFTW_VERSION_$(FFTW_VERSION) -DASM_F2I_$(ASM_F2I) -ggdb
 
Index: ZynAddSubFX-2.4.3/src/Makefile.inc
===================================================================
--- ZynAddSubFX-2.4.3.orig/src/Makefile.inc
+++ ZynAddSubFX-2.4.3/src/Makefile.inc
@@ -31,7 +31,7 @@ LINUX_MIDIIN=ALSA
 #LINUX_AUDIOOUT=OSS_AND_JACK
 LINUX_AUDIOOUT=OSS
 #LINUX_AUDIOOUT=NONE
-#LINUX_AUDIOOUT=JACK
+LINUX_AUDIOOUT=JACK
 #LINUX_AUDIOOUT=JACK_RT     JACK_RT support is broken
 #for PortAudio (PA)
 #LINUX_AUDIOOUT=PA
