--- client/Makefile.orig	2009-09-12 01:19:42.000000000 +0300
+++ client/Makefile	2010-02-04 00:05:39.998887523 +0200
@@ -63,10 +63,7 @@
 	gzip -9 man/smoltDeleteProfile.1 > $(DATADIR)/man/man1/smoltDeleteProfile.1.gz
 	gzip -9 man/smoltGui.1 > $(DATADIR)/man/man1/smoltGui.1.gz
 	
-	ln -sf $(DATADIR)/$(NAME)/client/sendProfile.py $(BINDIR)/smoltSendProfile
-	ln -sf $(DATADIR)/$(NAME)/client/deleteProfile.py $(BINDIR)/smoltDeleteProfile
-	ln -sf $(DATADIR)/$(NAME)/client/smoltGui.py $(BINDIR)/smoltGui
-	ln -sf $(SMOLTCONFIGDIR)/config.py $(DATADIR)/$(NAME)/client/config.py
+
 	
 	chmod +x $(DATADIR)/$(NAME)/client/*Profile.py
 	chmod +x $(DATADIR)/$(NAME)/client/smoltGui.py
@@ -84,17 +81,13 @@
 
 post-install: install-main
 
-	mkdir -p $(ETC)/init.d/
-	mkdir -p $(ETC)/cron.d/
-	cp -adv smolt-init $(ETC)/init.d/smolt
-	cp -adv smolt.cron.monthly $(ETC)/cron.d/smolt
+
 	
 uuid:
 	python makeuuid.py $(SMOLTCONFIGDIR)/hw-uuid True
 	
 cron:
-	python create_monthly.py > smolt.cron.monthly
-	cp -adv smolt.cron.monthly $(ETC)/cron.d/smolt
+
 	
 monkey: 
 	echo $(abspath $(DESTDIR))	
