--- Makefile.orig	2005-11-21 23:20:33.000000000 +0200
+++ Makefile	2011-06-20 19:04:35.122000050 +0300
@@ -1,3 +1,3 @@
 # add -noassert for speedup
 all: freetennis.ml 
-	ocamlopt   -I +camlimages  -I +lablGL -I +lablgtk2    -I +sdl -o freetennis  bigarray.cmxa sdl.cmxa lablgtk.cmxa lablgl.cmxa  ci_core.cmxa  sdlmixer.cmxa sdlttf.cmxa unix.cmxa freetennis.ml
+	ocamlc   -I +camlimages  -I +lablGL -I +lablgtk2    -I +sdl -o freetennis  bigarray.cma sdl.cma lablgtk.cma lablgl.cma  camlimages_core.cma  sdlmixer.cma sdlttf.cma unix.cma freetennis.ml
