/* automatically generated from xfdesktop-settings-appearance-frame-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_appearance_frame_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_appearance_frame_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_appearance_frame_ui[] =
#endif
{
  "<?xml version=\"1.0\"?>\n<!--Generated with glade3 3.4.5 on Sun Nov 16 "
  "16:39:43 2008 -->\n<interface>\n  <object class=\"GtkAdjustment\" id=\""
  "adjustment1\">\n    <property name=\"upper\">127</property>\n    <prope"
  "rty name=\"lower\">-128</property>\n    <property name=\"page_increment"
  "\">10</property>\n    <property name=\"step_increment\">1</property>\n "
  "   <property name=\"page_size\">0</property>\n    <property name=\"valu"
  "e\">0</property>\n  </object>\n  <object class=\"GtkAdjustment\" id=\"a"
  "djustment2\">\n    <property name=\"upper\">10</property>\n    <propert"
  "y name=\"lower\">-10</property>\n    <property name=\"page_increment\">"
  "10</property>\n    <property name=\"step_increment\">0.1000000000000000"
  "1</property>\n    <property name=\"page_size\">0</property>\n    <prope"
  "rty name=\"value\">1</property>\n  </object>\n  <object class=\"GtkAdju"
  "stment\" id=\"adjustment3\">\n    <property name=\"upper\">65535</prope"
  "rty>\n    <property name=\"lower\">1</property>\n    <property name=\"p"
  "age_increment\">10</property>\n    <property name=\"step_increment\">1<"
  "/property>\n    <property name=\"page_size\">0</property>\n    <propert"
  "y name=\"value\">10</property>\n  </object>\n  <object class=\"GtkListS"
  "tore\" id=\"model1\">\n    <columns>\n      <column type=\"gchararray\""
  "/>\n    </columns>\n    <data>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Auto</col>\n      </row>\n      <row>\n        <col id"
  "=\"0\" translatable=\"yes\">Centered</col>\n      </row>\n      <row>\n"
  "        <col id=\"0\" translatable=\"yes\">Tiled</col>\n      </row>\n "
  "     <row>\n        <col id=\"0\" translatable=\"yes\">Stretched</col>\n"
  "      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">S"
  "caled</col>\n      </row>\n      <row>\n        <col id=\"0\" translata"
  "ble=\"yes\">Zoomed</col>\n      </row>\n    </data>\n  </object>\n  <ob"
  "ject class=\"GtkListStore\" id=\"model2\">\n    <columns>\n      <colum"
  "n type=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n     "
  "   <col id=\"0\" translatable=\"yes\">Solid color</col>\n      </row>\n"
  "      <row>\n        <col id=\"0\" translatable=\"yes\">Horizontal grad"
  "ient</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Vertical gradient</col>\n      </row>\n      <row>\n        "
  "<col id=\"0\" translatable=\"yes\">Transparent</col>\n      </row>\n   "
  " </data>\n  </object>\n  <object class=\"GtkAlignment\" id=\"alignment_"
  "settings\">\n    <property name=\"visible\">True</property>\n    <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n    <"
  "property name=\"border_width\">12</property>\n    <property name=\"left"
  "_padding\">6</property>\n    <child>\n      <object class=\"GtkVBox\" i"
  "d=\"vbox1\">\n        <property name=\"visible\">True</property>\n     "
  "   <property name=\"spacing\">6</property>\n        <child>\n          "
  "<object class=\"GtkHBox\" id=\"hbox1\">\n            <property name=\"v"
  "isible\">True</property>\n            <property name=\"spacing\">12</pr"
  "operty>\n            <child>\n              <object class=\"GtkFrame\" "
  "id=\"frame_image_list\">\n                <property name=\"visible\">Tr"
  "ue</property>\n                <property name=\"label_xalign\">0</prope"
  "rty>\n                <property name=\"shadow_type\">GTK_SHADOW_NONE</p"
  "roperty>\n                <child>\n                  <object class=\"Gt"
  "kAlignment\" id=\"alignment7\">\n                    <property name=\"v"
  "isible\">True</property>\n                    <property name=\"top_padd"
  "ing\">6</property>\n                    <child>\n                      "
  "<object class=\"GtkVBox\" id=\"vbox3\">\n                        <prope"
  "rty name=\"visible\">True</property>\n                        <property"
  " name=\"spacing\">6</property>\n                        <child>\n      "
  "                    <object class=\"GtkScrolledWindow\" id=\"scrolledwi"
  "ndow1\">\n                            <property name=\"visible\">True</"
  "property>\n                            <property name=\"can_focus\">Tru"
  "e</property>\n                            <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                            "
  "<property name=\"hscrollbar_policy\">GTK_POLICY_AUTOMATIC</property>\n "
  "                           <property name=\"vscrollbar_policy\">GTK_POL"
  "ICY_AUTOMATIC</property>\n                            <property name=\""
  "shadow_type\">GTK_SHADOW_ETCHED_IN</property>\n                        "
  "    <child>\n                              <object class=\"GtkTreeView\""
  " id=\"treeview_imagelist\">\n                                <property "
  "name=\"visible\">True</property>\n                                <prop"
  "erty name=\"can_focus\">True</property>\n                              "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                                <property name=\"headers_visible\">F"
  "alse</property>\n                                <property name=\"searc"
  "h_column\">1</property>\n                              </object>\n     "
  "                       </child>\n                          </object>\n "
  "                       </child>\n                        <child>\n     "
  "                     <object class=\"GtkHBox\" id=\"hbox3\">\n         "
  "                   <property name=\"visible\">True</property>\n        "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                            <property name=\"spaci"
  "ng\">3</property>\n                            <child>\n               "
  "               <object class=\"GtkButton\" id=\"btn_plus\">\n          "
  "                      <property name=\"visible\">True</property>\n     "
  "                           <property name=\"can_focus\">True</property>"
  "\n                                <property name=\"receives_default\">T"
  "rue</property>\n                                <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "          <property name=\"tooltip-text\" translatable=\"yes\">Add an i"
  "mage to the list</property>\n                                <signal ha"
  "ndler=\"add_clicked\" name=\"clicked\"/>\n                             "
  "   <child>\n                                  <object class=\"GtkImage\""
  " id=\"image1\">\n                                    <property name=\"v"
  "isible\">True</property>\n                                    <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                            <property name=\"stock\">gtk-add</property>"
  "\n                                    <property name=\"icon_size\">1</p"
  "roperty>\n                                  </object>\n                "
  "                </child>\n                              </object>\n    "
  "                          <packing>\n                                <p"
  "roperty name=\"expand\">False</property>\n                             "
  " </packing>\n                            </child>\n                    "
  "        <child>\n                              <object class=\"GtkButto"
  "n\" id=\"btn_minus\">\n                                <property name=\""
  "visible\">True</property>\n                                <property na"
  "me=\"sensitive\">False</property>\n                                <pro"
  "perty name=\"can_focus\">True</property>\n                             "
  "   <property name=\"receives_default\">True</property>\n               "
  "                 <property name=\"events\">GDK_POINTER_MOTION_MASK | GD"
  "K_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE"
  "_MASK</property>\n                                <property name=\"tool"
  "tip-text\" translatable=\"yes\">Remove the selected image(s) from the l"
  "ist</property>\n                                <signal handler=\"remov"
  "e_clicked\" name=\"clicked\"/>\n                                <child>"
  "\n                                  <object class=\"GtkImage\" id=\"ima"
  "ge2\">\n                                    <property name=\"visible\">"
  "True</property>\n                                    <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "                   <property name=\"stock\">gtk-remove</property>\n    "
  "                                <property name=\"icon_size\">1</propert"
  "y>\n                                  </object>\n                      "
  "          </child>\n                              </object>\n          "
  "                    <packing>\n                                <propert"
  "y name=\"expand\">False</property>\n                                <pr"
  "operty name=\"fill\">False</property>\n                                "
  "<property name=\"position\">1</property>\n                             "
  " </packing>\n                            </child>\n                    "
  "        <child>\n                              <object class=\"GtkButto"
  "n\" id=\"btn_newlist\">\n                                <property name"
  "=\"visible\">True</property>\n                                <property"
  " name=\"sensitive\">False</property>\n                                <"
  "property name=\"can_focus\">True</property>\n                          "
  "      <property name=\"receives_default\">True</property>\n            "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                                <property name=\"t"
  "ooltip-text\" translatable=\"yes\">Create a new list, or load an existi"
  "ng one</property>\n                                <child>\n           "
  "                       <object class=\"GtkImage\" id=\"image3\">\n     "
  "                               <property name=\"visible\">True</propert"
  "y>\n                                    <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "      <property name=\"stock\">gtk-new</property>\n                    "
  "                <property name=\"icon_size\">1</property>\n            "
  "                      </object>\n                                </chil"
  "d>\n                              </object>\n                          "
  "    <packing>\n                                <property name=\"expand\""
  ">False</property>\n                                <property name=\"pos"
  "ition\">4</property>\n                              </packing>\n       "
  "                     </child>\n                            <child>\n   "
  "                           <object class=\"GtkLabel\" id=\"label8\">\n "
  "                               <property name=\"visible\">True</propert"
  "y>\n                                <property name=\"events\">GDK_POINT"
  "ER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK |"
  " GDK_BUTTON_RELEASE_MASK</property>\n                                <p"
  "roperty name=\"label\" translatable=\"yes\">St_yle:</property>\n       "
  "                         <property name=\"use_underline\">True</propert"
  "y>\n                                <property name=\"mnemonic_widget\">"
  "combo_style</property>\n                              </object>\n      "
  "                        <packing>\n                                <pro"
  "perty name=\"expand\">False</property>\n                               "
  " <property name=\"padding\">3</property>\n                             "
  "   <property name=\"pack_type\">GTK_PACK_END</property>\n              "
  "                  <property name=\"position\">3</property>\n           "
  "                   </packing>\n                            </child>\n  "
  "                          <child>\n                              <objec"
  "t class=\"GtkComboBox\" id=\"combo_style\">\n                          "
  "      <property name=\"visible\">True</property>\n                     "
  "           <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POIN"
  "TER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK<"
  "/property>\n                                <property name=\"tooltip-te"
  "xt\" translatable=\"yes\">Specify how the image will be resized to fit "
  "the screen</property>\n                                <signal handler="
  "\"image_style_changed\" name=\"changed\"/>\n                           "
  "     <property name=\"model\">model1</property>\n                      "
  "          <child>\n                                  <object class=\"Gt"
  "kCellRendererText\" id=\"renderer1\"/>\n                               "
  "   <attributes>\n                                    <attribute name=\""
  "text\">0</attribute>\n                                  </attributes>\n"
  "                                </child>\n                             "
  " </object>\n                              <packing>\n                  "
  "              <property name=\"expand\">False</property>\n             "
  "                   <property name=\"pack_type\">GTK_PACK_END</property>"
  "\n                                <property name=\"position\">2</proper"
  "ty>\n                              </packing>\n                        "
  "    </child>\n                          </object>\n                    "
  "      <packing>\n                            <property name=\"expand\">"
  "False</property>\n                            <property name=\"position"
  "\">1</property>\n                          </packing>\n                "
  "        </child>\n                      </object>\n                    "
  "</child>\n                  </object>\n                </child>\n      "
  "          <child type=\"label\">\n                  <object class=\"Gtk"
  "Label\" id=\"label4\">\n                    <property name=\"visible\">"
  "True</property>\n                    <property name=\"label\" translata"
  "ble=\"yes\">&lt;b&gt;Images&lt;/b&gt;</property>\n                    <"
  "property name=\"use_markup\">True</property>\n                  </objec"
  "t>\n                </child>\n              </object>\n            </ch"
  "ild>\n            <child>\n              <object class=\"GtkVBox\" id=\""
  "vbox12\">\n                <property name=\"visible\">True</property>\n"
  "                <property name=\"spacing\">6</property>\n              "
  "  <child>\n                  <object class=\"GtkFrame\" id=\"frame2\">\n"
  "                    <property name=\"visible\">True</property>\n       "
  "             <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_PO"
  "INTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MAS"
  "K</property>\n                    <property name=\"label_xalign\">0</pr"
  "operty>\n                    <property name=\"shadow_type\">GTK_SHADOW_"
  "NONE</property>\n                    <child>\n                      <ob"
  "ject class=\"GtkAlignment\" id=\"alignment2\">\n                       "
  " <property name=\"visible\">True</property>\n                        <p"
  "roperty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HI"
  "NT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n "
  "                       <property name=\"border_width\">6</property>\n  "
  "                      <property name=\"left_padding\">6</property>\n   "
  "                     <child>\n                          <object class=\""
  "GtkVBox\" id=\"vbox5\">\n                            <property name=\"v"
  "isible\">True</property>\n                            <child>\n        "
  "                      <object class=\"GtkRadioButton\" id=\"radio_singl"
  "eimage\">\n                                <property name=\"visible\">T"
  "rue</property>\n                                <property name=\"can_fo"
  "cus\">True</property>\n                                <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                <property name=\"tooltip-text\" translatable=\"yes\">Se"
  "lect a single image as the backdrop</property>\n                       "
  "         <property name=\"label\" translatable=\"yes\">_Single image</p"
  "roperty>\n                                <property name=\"use_underlin"
  "e\">True</property>\n                                <property name=\"a"
  "ctive\">True</property>\n                                <property name"
  "=\"draw_indicator\">True</property>\n                                <s"
  "ignal handler=\"image_type_changed\" name=\"toggled\"/>\n              "
  "                </object>\n                              <packing>\n   "
  "                             <property name=\"expand\">False</property>"
  "\n                              </packing>\n                           "
  " </child>\n                            <child>\n                       "
  "       <object class=\"GtkRadioButton\" id=\"radio_imagelist\">\n      "
  "                          <property name=\"visible\">True</property>\n "
  "                               <property name=\"can_focus\">True</prope"
  "rty>\n                                <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n                                "
  "<property name=\"tooltip-text\" translatable=\"yes\">Automatically pick"
  " a random image from a list file</property>\n                          "
  "      <property name=\"label\" translatable=\"yes\">Image _list</proper"
  "ty>\n                                <property name=\"use_underline\">T"
  "rue</property>\n                                <property name=\"draw_i"
  "ndicator\">True</property>\n                                <property n"
  "ame=\"group\">radio_singleimage</property>\n                           "
  "     <signal handler=\"image_type_changed\" name=\"toggled\"/>\n       "
  "                       </object>\n                              <packin"
  "g>\n                                <property name=\"expand\">False</pr"
  "operty>\n                                <property name=\"position\">1<"
  "/property>\n                              </packing>\n                 "
  "           </child>\n                            <child>\n             "
  "                 <object class=\"GtkRadioButton\" id=\"radio_none\">\n "
  "                               <property name=\"visible\">True</propert"
  "y>\n                                <property name=\"can_focus\">True</"
  "property>\n                                <property name=\"tooltip-tex"
  "t\" translatable=\"yes\">Don\'t display an image at all</property>\n   "
  "                             <property name=\"label\" translatable=\"ye"
  "s\">_None</property>\n                                <property name=\""
  "use_underline\">True</property>\n                                <prope"
  "rty name=\"draw_indicator\">True</property>\n                          "
  "      <property name=\"group\">radio_singleimage</property>\n          "
  "                    </object>\n                              <packing>\n"
  "                                <property name=\"expand\">False</proper"
  "ty>\n                                <property name=\"position\">2</pro"
  "perty>\n                              </packing>\n                     "
  "       </child>\n                          </object>\n                 "
  "       </child>\n                      </object>\n                    <"
  "/child>\n                    <child type=\"label\">\n                  "
  "    <object class=\"GtkLabel\" id=\"label9\">\n                        "
  "<property name=\"visible\">True</property>\n                        <pr"
  "operty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HIN"
  "T_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n  "
  "                      <property name=\"label\" translatable=\"yes\">&lt"
  ";b&gt;Image&lt;/b&gt;</property>\n                        <property nam"
  "e=\"use_markup\">True</property>\n                      </object>\n    "
  "                </child>\n                  </object>\n                "
  "  <packing>\n                    <property name=\"expand\">False</prope"
  "rty>\n                  </packing>\n                </child>\n         "
  "       <child>\n                  <object class=\"GtkFrame\" id=\"frame"
  "1\">\n                    <property name=\"visible\">True</property>\n "
  "                   <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                    <property name=\"label_xalign\""
  ">0</property>\n                    <property name=\"shadow_type\">GTK_S"
  "HADOW_NONE</property>\n                    <child>\n                   "
  "   <object class=\"GtkAlignment\" id=\"alignment3\">\n                 "
  "       <property name=\"visible\">True</property>\n                    "
  "    <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOT"
  "ION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</proper"
  "ty>\n                        <property name=\"border_width\">6</propert"
  "y>\n                        <property name=\"left_padding\">6</property"
  ">\n                        <child>\n                          <object c"
  "lass=\"GtkVBox\" id=\"vbox13\">\n                            <property "
  "name=\"visible\">True</property>\n                            <property"
  " name=\"spacing\">6</property>\n                            <child>\n  "
  "                            <object class=\"GtkComboBox\" id=\"combo_co"
  "lors\">\n                                <property name=\"visible\">Tru"
  "e</property>\n                                <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "        <property name=\"tooltip-text\" translatable=\"yes\">Specify th"
  "e style of the color drawn behind the backdrop image</property>\n      "
  "                          <signal handler=\"color_style_changed\" name="
  "\"changed\"/>\n                                <property name=\"model\""
  ">model2</property>\n                                <child>\n          "
  "                        <object class=\"GtkCellRendererText\" id=\"rend"
  "erer2\"/>\n                                  <attributes>\n            "
  "                        <attribute name=\"text\">0</attribute>\n       "
  "                           </attributes>\n                             "
  "   </child>\n                              </object>\n                 "
  "             <packing>\n                                <property name="
  "\"expand\">False</property>\n                              </packing>\n"
  "                            </child>\n                            <chil"
  "d>\n                              <object class=\"GtkHBox\" id=\"hbox2\""
  ">\n                                <property name=\"visible\">True</pro"
  "perty>\n                                <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "  <property name=\"spacing\">12</property>\n                           "
  "     <child>\n                                  <object class=\"GtkColo"
  "rButton\" id=\"color1_btn\">\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <property name=\"can_focus\">True</property>\n                     "
  "               <property name=\"receives_default\">True</property>\n   "
  "                                 <property name=\"events\">GDK_POINTER_"
  "MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | G"
  "DK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            "
  "                        <property name=\"tooltip-text\" translatable=\""
  "yes\">Specifies the solid color, or the \"left\" or \"top\" color of th"
  "e gradient</property>\n                                    <property na"
  "me=\"title\" translatable=\"yes\">Select First Color</property>\n      "
  "                              <property name=\"color\">#151522223333</p"
  "roperty>\n                                    <signal handler=\"color1_"
  "changed\" name=\"color_set\"/>\n                                  </obj"
  "ect>\n                                  <packing>\n                    "
  "                <property name=\"expand\">False</property>\n           "
  "                       </packing>\n                                </ch"
  "ild>\n                                <child>\n                        "
  "          <object class=\"GtkColorButton\" id=\"color2_btn\">\n        "
  "                            <property name=\"visible\">True</property>\n"
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                    <property name=\"receive"
  "s_default\">True</property>\n                                    <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                                    <property name="
  "\"tooltip-text\" translatable=\"yes\">Specifies the \"right\" or \"bott"
  "om\" color of the gradient</property>\n                                "
  "    <property name=\"title\" translatable=\"yes\">Select Second Color</"
  "property>\n                                    <property name=\"color\""
  ">#151522223333</property>\n                                    <signal "
  "handler=\"color2_changed\" name=\"color_set\"/>\n                      "
  "            </object>\n                                  <packing>\n   "
  "                                 <property name=\"expand\">False</prope"
  "rty>\n                                    <property name=\"position\">1"
  "</property>\n                                  </packing>\n            "
  "                    </child>\n                              </object>\n"
  "                              <packing>\n                              "
  "  <property name=\"position\">1</property>\n                           "
  "   </packing>\n                            </child>\n                  "
  "        </object>\n                        </child>\n                  "
  "    </object>\n                    </child>\n                    <child"
  " type=\"label\">\n                      <object class=\"GtkLabel\" id=\""
  "label7\">\n                        <property name=\"visible\">True</pro"
  "perty>\n                        <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                        <property name"
  "=\"label\" translatable=\"yes\">&lt;b&gt;Colors&lt;/b&gt;</property>\n "
  "                       <property name=\"use_markup\">True</property>\n "
  "                     </object>\n                    </child>\n         "
  "         </object>\n                  <packing>\n                    <p"
  "roperty name=\"expand\">False</property>\n                    <property"
  " name=\"position\">1</property>\n                  </packing>\n        "
  "        </child>\n              </object>\n              <packing>\n   "
  "             <property name=\"position\">1</property>\n                "
  "<property name=\"expand\">False</property>\n              </packing>\n "
  "           </child>\n          </object>\n        </child>\n        <ch"
  "ild>\n          <object class=\"GtkFrame\" id=\"frame3\">\n            "
  "<property name=\"visible\">True</property>\n            <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            <p"
  "roperty name=\"label_xalign\">0</property>\n            <property name="
  "\"shadow_type\">GTK_SHADOW_NONE</property>\n            <child>\n      "
  "        <object class=\"GtkAlignment\" id=\"alignment4\">\n            "
  "    <property name=\"visible\">True</property>\n                <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "          <property name=\"border_width\">6</property>\n               "
  " <property name=\"left_padding\">6</property>\n                <child>\n"
  "                  <object class=\"GtkVBox\" id=\"vbox14\">\n           "
  "         <property name=\"visible\">True</property>\n                  "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                    <property name=\"spacing\">6</property>\n       "
  "             <child>\n                      <object class=\"GtkHBox\" i"
  "d=\"hbox5\">\n                        <property name=\"visible\">True</"
  "property>\n                        <property name=\"events\">GDK_POINTE"
  "R_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | "
  "GDK_BUTTON_RELEASE_MASK</property>\n                        <property n"
  "ame=\"spacing\">4</property>\n                        <child>\n        "
  "                  <object class=\"GtkLabel\" id=\"label19\">\n         "
  "                   <property name=\"visible\">True</property>\n        "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                            <property name=\"label"
  "\" translatable=\"yes\">B_rightness:</property>\n                      "
  "      <property name=\"use_underline\">True</property>\n               "
  "             <property name=\"mnemonic_widget\">slider_brightness</prop"
  "erty>\n                          </object>\n                          <"
  "packing>\n                            <property name=\"expand\">False</"
  "property>\n                          </packing>\n                      "
  "  </child>\n                        <child>\n                          "
  "<object class=\"GtkHScale\" id=\"slider_brightness\">\n                "
  "            <property name=\"visible\">True</property>\n               "
  "             <property name=\"can_focus\">True</property>\n            "
  "                <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK"
  "_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_"
  "MASK</property>\n                            <property name=\"tooltip-t"
  "ext\" translatable=\"yes\">Increase or decrease the brightness of the f"
  "inal image</property>\n                            <property name=\"upd"
  "ate_policy\">GTK_UPDATE_DISCONTINUOUS</property>\n                     "
  "       <property name=\"adjustment\">adjustment1</property>\n          "
  "                  <property name=\"digits\">0</property>\n             "
  "               <property name=\"value_pos\">GTK_POS_RIGHT</property>\n "
  "                           <signal handler=\"brightness_changed\" name="
  "\"value_changed\"/>\n                          </object>\n             "
  "             <packing>\n                            <property name=\"po"
  "sition\">1</property>\n                          </packing>\n          "
  "              </child>\n                      </object>\n              "
  "        <packing>\n                        <property name=\"expand\">Fa"
  "lse</property>\n                      </packing>\n                    <"
  "/child>\n                    <child>\n                      <object cla"
  "ss=\"GtkHBox\" id=\"hbox6\">\n                        <property name=\""
  "visible\">True</property>\n                        <property name=\"eve"
  "nts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTT"
  "ON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                   "
  "     <property name=\"spacing\">12</property>\n                        "
  "<child>\n                          <object class=\"GtkLabel\" id=\"labe"
  "l20\">\n                            <property name=\"visible\">True</pr"
  "operty>\n                            <property name=\"events\">GDK_POIN"
  "TER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK "
  "| GDK_BUTTON_RELEASE_MASK</property>\n                            <prop"
  "erty name=\"label\" translatable=\"yes\">Sa_turation:</property>\n     "
  "                       <property name=\"use_underline\">True</property>"
  "\n                            <property name=\"mnemonic_widget\">slider"
  "_saturation</property>\n                          </object>\n          "
  "                <packing>\n                            <property name=\""
  "expand\">False</property>\n                          </packing>\n      "
  "                  </child>\n                        <child>\n          "
  "                <object class=\"GtkHScale\" id=\"slider_saturation\">\n"
  "                            <property name=\"visible\">True</property>\n"
  "                            <property name=\"can_focus\">True</property"
  ">\n                            <property name=\"events\">GDK_POINTER_MO"
  "TION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_"
  "BUTTON_RELEASE_MASK</property>\n                            <property n"
  "ame=\"tooltip-text\" translatable=\"yes\">Increase or decrease the colo"
  "r saturation of the final image</property>\n                           "
  " <property name=\"update_policy\">GTK_UPDATE_DISCONTINUOUS</property>\n"
  "                            <property name=\"adjustment\">adjustment2</"
  "property>\n                            <property name=\"value_pos\">GTK"
  "_POS_RIGHT</property>\n                            <signal handler=\"sa"
  "turation_changed\" name=\"value_changed\"/>\n                          "
  "</object>\n                          <packing>\n                       "
  "     <property name=\"position\">1</property>\n                        "
  "  </packing>\n                        </child>\n                      <"
  "/object>\n                      <packing>\n                        <pro"
  "perty name=\"expand\">False</property>\n                        <proper"
  "ty name=\"position\">1</property>\n                      </packing>\n  "
  "                  </child>\n                  </object>\n              "
  "  </child>\n              </object>\n            </child>\n            "
  "<child type=\"label\">\n              <object class=\"GtkLabel\" id=\"l"
  "abel21\">\n                <property name=\"visible\">True</property>\n"
  "                <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK"
  "_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_"
  "MASK</property>\n                <property name=\"label\" translatable="
  "\"yes\">&lt;b&gt;Adjustments&lt;/b&gt;</property>\n                <pro"
  "perty name=\"use_markup\">True</property>\n              </object>\n   "
  "         </child>\n          </object>\n          <packing>\n          "
  "  <property name=\"expand\">False</property>\n            <property nam"
  "e=\"position\">1</property>\n          </packing>\n        </child>\n  "
  "      <child>\n          <object class=\"GtkHBox\" id=\"hbox9\">\n     "
  "       <property name=\"visible\">True</property>\n            <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "     <property name=\"spacing\">4</property>\n            <child>\n    "
  "          <object class=\"GtkCheckButton\" id=\"chk_cycle_backdrop\">\n"
  "                <property name=\"visible\">True</property>\n           "
  "     <property name=\"sensitive\">False</property>\n                <pr"
  "operty name=\"can_focus\">True</property>\n                <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "     <property name=\"label\" translatable=\"yes\">_Change the backgrou"
  "nd (in minutes):</property>\n                <property name=\"tooltip-t"
  "ext\" translatable=\"yes\">While in image list mode, select this option"
  " to automatically select a different background from the image list aft"
  "er a set number of minutes.</property>\n                <property name="
  "\"use_underline\">True</property>\n                <property name=\"dra"
  "w_indicator\">True</property>\n              </object>\n              <"
  "packing>\n                <property name=\"expand\">False</property>\n "
  "             </packing>\n            </child>\n          <child>\n     "
  "       <object class=\"GtkSpinButton\" id=\"spin_backdrop_time_minutes\""
  ">\n              <property name=\"visible\">True</property>\n          "
  "    <property name=\"sensitive\">False</property>\n              <prope"
  "rty name=\"can_focus\">True</property>\n              <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              <p"
  "roperty name=\"adjustment\">adjustment3</property>\n              <prop"
  "erty name=\"tooltip-text\" translatable=\"yes\">Number of minutes befor"
  "e a different background is randomly selected from the list.</property>"
  "\n            </object>\n            <packing>\n              <property"
  " name=\"expand\">False</property>\n              <property name=\"posit"
  "ion\">2</property>\n            </packing>\n          </child>\n       "
  " </object>\n        <packing>\n          <property name=\"expand\">Fals"
  "e</property>\n          <property name=\"position\">2</property>\n     "
  "   </packing>\n      </child>\n      <child>\n        <object class=\"G"
  "tkCheckButton\" id=\"chk_xinerama_stretch\">\n          <property name="
  "\"visible\">True</property>\n          <property name=\"sensitive\">Fal"
  "se</property>\n          <property name=\"can_focus\">True</property>\n"
  "          <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINT"
  "ER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</"
  "property>\n          <property name=\"label\" translatable=\"yes\">St_r"
  "etch this background across all monitors.</property>\n          <proper"
  "ty name=\"tooltip-text\" translatable=\"yes\">When multiple monitors ar"
  "e present, select this option to stretch the current background over al"
  "l of them.</property>\n          <property name=\"use_underline\">True<"
  "/property>\n          <property name=\"draw_indicator\">True</property>"
  "\n        </object>\n        <packing>\n          <property name=\"expa"
  "nd\">False</property>\n          <property name=\"position\">3</propert"
  "y>\n        </packing>\n      </child>\n      </object>\n    </child>\n"
  "  </object>\n</interface>\n"
};

static const unsigned xfdesktop_settings_appearance_frame_ui_length = 36419u;

