/* automatically generated from xfdesktop-settings-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\"?>\n<!--Generated with glade3 3.4.5 on Sun Nov 16 "
  "16:39:43 2008 -->\n<interface>\n  <object class=\"GtkAdjustment\" id=\""
  "adjustment1\">\n    <property name=\"upper\">127</property>\n    <prope"
  "rty name=\"lower\">-128</property>\n    <property name=\"page_increment"
  "\">10</property>\n    <property name=\"step_increment\">1</property>\n "
  "   <property name=\"page_size\">0</property>\n    <property name=\"valu"
  "e\">0</property>\n  </object>\n  <object class=\"GtkAdjustment\" id=\"a"
  "djustment2\">\n    <property name=\"upper\">10</property>\n    <propert"
  "y name=\"lower\">-10</property>\n    <property name=\"page_increment\">"
  "10</property>\n    <property name=\"step_increment\">0.1000000000000000"
  "1</property>\n    <property name=\"page_size\">0</property>\n    <prope"
  "rty name=\"value\">1</property>\n  </object>\n  <object class=\"GtkAdju"
  "stment\" id=\"adjustment3\">\n    <property name=\"upper\">192</propert"
  "y>\n    <property name=\"lower\">8</property>\n    <property name=\"pag"
  "e_increment\">10</property>\n    <property name=\"step_increment\">1</p"
  "roperty>\n    <property name=\"page_size\">0</property>\n    <property "
  "name=\"value\">36</property>\n  </object>\n  <object class=\"GtkAdjustm"
  "ent\" id=\"adjustment4\">\n    <property name=\"upper\">144</property>\n"
  "    <property name=\"lower\">4</property>\n    <property name=\"page_in"
  "crement\">10</property>\n    <property name=\"step_increment\">1</prope"
  "rty>\n    <property name=\"page_size\">0</property>\n    <property name"
  "=\"value\">12</property>\n  </object>\n  <object class=\"GtkAdjustment\""
  " id=\"adjustment5\">\n    <property name=\"upper\">100</property>\n    "
  "<property name=\"lower\">0</property>\n    <property name=\"page_increm"
  "ent\">10</property>\n    <property name=\"step_increment\">1</property>"
  "\n    <property name=\"page_size\">0</property>\n    <property name=\"v"
  "alue\">40</property>\n  </object>\n  <object class=\"GtkListStore\" id="
  "\"model1\">\n    <columns>\n      <column type=\"gchararray\"/>\n    </"
  "columns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">Auto</col>\n      </row>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Centered</col>\n      </row>\n      <row>\n        <co"
  "l id=\"0\" translatable=\"yes\">Tiled</col>\n      </row>\n      <row>\n"
  "        <col id=\"0\" translatable=\"yes\">Stretched</col>\n      </row"
  ">\n      <row>\n        <col id=\"0\" translatable=\"yes\">Scaled</col>"
  "\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Zoomed</col>\n      </row>\n    </data>\n  </object>\n  <object class="
  "\"GtkListStore\" id=\"model2\">\n    <columns>\n      <column type=\"gc"
  "hararray\"/>\n    </columns>\n    <data>\n      <row>\n        <col id="
  "\"0\" translatable=\"yes\">Solid color</col>\n      </row>\n      <row>"
  "\n        <col id=\"0\" translatable=\"yes\">Horizontal gradient</col>\n"
  "      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">V"
  "ertical gradient</col>\n      </row>\n      <row>\n        <col id=\"0\""
  " translatable=\"yes\">Transparent</col>\n      </row>\n    </data>\n  <"
  "/object>\n  <object class=\"GtkListStore\" id=\"model3\">\n    <columns"
  ">\n      <column type=\"gchararray\"/>\n    </columns>\n    <data>\n   "
  "   <row>\n        <col id=\"0\" translatable=\"yes\">Left</col>\n      "
  "</row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Middle<"
  "/col>\n      </row>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">Right</col>\n      </row>\n    </data>\n  </object>\n  <object cl"
  "ass=\"GtkListStore\" id=\"model4\">\n    <columns>\n      <column type="
  "\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">None</col>\n      </row>\n      <row>\n "
  "       <col id=\"0\" translatable=\"yes\">Shift</col>\n      </row>\n  "
  "    <row>\n        <col id=\"0\" translatable=\"yes\">Alt</col>\n      "
  "</row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Control"
  "</col>\n      </row>\n    </data>\n  </object>\n  <object class=\"GtkLi"
  "stStore\" id=\"model5\">\n    <columns>\n      <column type=\"gchararra"
  "y\"/>\n    </columns>\n    <data>\n      <row>\n        <col id=\"0\" t"
  "ranslatable=\"yes\">Left</col>\n      </row>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">Middle</col>\n      </row>\n      <row>\n"
  "        <col id=\"0\" translatable=\"yes\">Right</col>\n      </row>\n "
  "   </data>\n  </object>\n  <object class=\"GtkListStore\" id=\"model6\""
  ">\n    <columns>\n      <column type=\"gchararray\"/>\n    </columns>\n"
  "    <data>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Non"
  "e</col>\n      </row>\n      <row>\n        <col id=\"0\" translatable="
  "\"yes\">Shift</col>\n      </row>\n      <row>\n        <col id=\"0\" t"
  "ranslatable=\"yes\">Alt</col>\n      </row>\n      <row>\n        <col "
  "id=\"0\" translatable=\"yes\">Control</col>\n      </row>\n    </data>\n"
  "  </object>\n  <object class=\"GtkListStore\" id=\"model7\">\n    <colu"
  "mns>\n      <column type=\"gchararray\"/>\n    </columns>\n    <data>\n"
  "      <row>\n        <col id=\"0\" translatable=\"yes\">None</col>\n   "
  "   </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Mini"
  "mized application icons</col>\n      </row>\n      <row>\n        <col "
  "id=\"0\" translatable=\"yes\">File/launcher icons</col>\n      </row>\n"
  "    </data>\n  </object>\n  <object class=\"XfceTitledDialog\" id=\"pre"
  "fs_dialog\">\n    <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n    <property name=\"title\" translatable=\"yes\">De"
  "sktop</property>\n    <property name=\"window_position\">GTK_WIN_POS_CE"
  "NTER_ON_PARENT</property>\n    <property name=\"icon_name\">preferences"
  "-desktop-wallpaper</property>\n    <property name=\"type_hint\">GDK_WIN"
  "DOW_TYPE_HINT_DIALOG</property>\n    <property name=\"has_separator\">F"
  "alse</property>\n    <property name=\"subtitle\" translatable=\"yes\">S"
  "et desktop background and menu and icon behavior</property>\n    <child"
  " internal-child=\"vbox\">\n      <object class=\"GtkVBox\" id=\"dialog-"
  "vbox1\">\n        <property name=\"visible\">True</property>\n        <"
  "property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_H"
  "INT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "        <property name=\"spacing\">2</property>\n        <child>\n     "
  "     <object class=\"GtkAlignment\" id=\"alignment1\">\n            <pr"
  "operty name=\"visible\">True</property>\n            <child>\n         "
  "     <object class=\"GtkNotebook\" id=\"notebook_settings\">\n         "
  "       <property name=\"visible\">True</property>\n                <pro"
  "perty name=\"can_focus\">True</property>\n                <property nam"
  "e=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | G"
  "DK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            "
  "    <property name=\"border_width\">6</property>\n                <chil"
  "d>\n                  <object class=\"GtkNotebook\" id=\"notebook_scree"
  "ns\">\n                    <property name=\"visible\">True</property>\n"
  "                    <property name=\"can_focus\">True</property>\n     "
  "               <property name=\"show_tabs\">False</property>\n         "
  "           <property name=\"show_border\">False</property>\n           "
  "         <child type=\"tab\">\n                      <placeholder/>\n  "
  "                  </child>\n                  </object>\n              "
  "  </child>\n                <child type=\"tab\">\n                  <ob"
  "ject class=\"GtkLabel\" id=\"label1\">\n                    <property n"
  "ame=\"visible\">True</property>\n                    <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "   <property name=\"label\" translatable=\"yes\">_Background</property>"
  "\n                    <property name=\"use_underline\">True</property>\n"
  "                  </object>\n                  <packing>\n             "
  "       <property name=\"tab_fill\">False</property>\n                  "
  "</packing>\n                </child>\n                <child>\n        "
  "          <object class=\"GtkVBox\" id=\"vbox4\">\n                    "
  "<property name=\"visible\">True</property>\n                    <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "              <property name=\"border_width\">12</property>\n          "
  "          <property name=\"spacing\">6</property>\n                    "
  "<child>\n                      <object class=\"GtkFrame\" id=\"frame4\""
  ">\n                        <property name=\"visible\">True</property>\n"
  "                        <property name=\"events\">GDK_POINTER_MOTION_MA"
  "SK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_"
  "RELEASE_MASK</property>\n                        <property name=\"label"
  "_xalign\">0</property>\n                        <property name=\"shadow"
  "_type\">GTK_SHADOW_NONE</property>\n                        <child>\n  "
  "                        <object class=\"GtkAlignment\" id=\"alignment5\""
  ">\n                            <property name=\"visible\">True</propert"
  "y>\n                            <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                            <property "
  "name=\"border_width\">6</property>\n                            <proper"
  "ty name=\"left_padding\">6</property>\n                            <chi"
  "ld>\n                              <object class=\"GtkVBox\" id=\"vbox7"
  "\">\n                                <property name=\"visible\">True</p"
  "roperty>\n                                <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                            "
  "    <property name=\"spacing\">6</property>\n                          "
  "      <child>\n                                  <object class=\"GtkChe"
  "ckButton\" id=\"chk_show_desktop_menu\">\n                             "
  "       <property name=\"visible\">True</property>\n                    "
  "                <property name=\"can_focus\">True</property>\n         "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                                    <proper"
  "ty name=\"label\" translatable=\"yes\">Show applications menu on _deskt"
  "op right click</property>\n                                    <propert"
  "y name=\"use_underline\">True</property>\n                             "
  "       <property name=\"active\">True</property>\n                     "
  "               <property name=\"draw_indicator\">True</property>\n     "
  "                             </object>\n                               "
  " </child>\n                                <child>\n                   "
  "               <object class=\"GtkAlignment\" id=\"box_menu_subopts\">\n"
  "                                    <property name=\"visible\">True</pr"
  "operty>\n                                    <property name=\"events\">"
  "GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRE"
  "SS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                         "
  "           <property name=\"bottom_padding\">6</property>\n            "
  "                        <property name=\"left_padding\">12</property>\n"
  "                                    <child>\n                          "
  "            <object class=\"GtkVBox\" id=\"vbox10\">\n                 "
  "                       <property name=\"visible\">True</property>\n    "
  "                                    <property name=\"events\">GDK_POINT"
  "ER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK |"
  " GDK_BUTTON_RELEASE_MASK</property>\n                                  "
  "      <property name=\"spacing\">6</property>\n                        "
  "                <child>\n                                          <obj"
  "ect class=\"GtkHBox\" id=\"hbox11\">\n                                 "
  "           <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POIN"
  "TER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK<"
  "/property>\n                                            <property name="
  "\"spacing\">12</property>\n                                            "
  "<child>\n                                              <object class=\""
  "GtkLabel\" id=\"label17\">\n                                           "
  "     <property name=\"visible\">True</property>\n                      "
  "                          <property name=\"events\">GDK_POINTER_MOTION_"
  "MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTO"
  "N_RELEASE_MASK</property>\n                                            "
  "    <property name=\"label\" translatable=\"yes\">_Button:</property>\n"
  "                                                <property name=\"use_un"
  "derline\">True</property>\n                                            "
  "    <property name=\"mnemonic_widget\">combobox1</property>\n          "
  "                                    </object>\n                        "
  "                      <packing>\n                                      "
  "          <property name=\"expand\">False</property>\n                 "
  "                             </packing>\n                              "
  "              </child>\n                                            <ch"
  "ild>\n                                              <object class=\"Gtk"
  "ComboBox\" id=\"combobox1\">\n                                         "
  "       <property name=\"visible\">True</property>\n                    "
  "                            <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n                                          "
  "      <property name=\"model\">model3</property>\n                     "
  "                           <child>\n                                   "
  "               <object class=\"GtkCellRendererText\" id=\"renderer3\"/>"
  "\n                                                  <attributes>\n     "
  "                                               <attribute name=\"text\""
  ">0</attribute>\n                                                  </att"
  "ributes>\n                                                </child>\n   "
  "                                           </object>\n                 "
  "                             <packing>\n                               "
  "                 <property name=\"expand\">False</property>\n          "
  "                                      <property name=\"position\">1</pr"
  "operty>\n                                              </packing>\n    "
  "                                        </child>\n                     "
  "                       <child>\n                                       "
  "       <object class=\"GtkLabel\" id=\"label18\">\n                    "
  "                            <property name=\"visible\">True</property>\n"
  "                                                <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "                          <property name=\"label\" translatable=\"yes\""
  ">Mo_difier:</property>\n                                               "
  " <property name=\"use_underline\">True</property>\n                    "
  "                            <property name=\"mnemonic_widget\">combobox"
  "2</property>\n                                              </object>\n"
  "                                              <packing>\n              "
  "                                  <property name=\"expand\">False</prop"
  "erty>\n                                                <property name=\""
  "position\">2</property>\n                                              "
  "</packing>\n                                            </child>\n     "
  "                                       <child>\n                       "
  "                       <object class=\"GtkComboBox\" id=\"combobox2\">\n"
  "                                                <property name=\"visibl"
  "e\">True</property>\n                                                <p"
  "roperty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HI"
  "NT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n "
  "                                               <property name=\"model\""
  ">model4</property>\n                                                <ch"
  "ild>\n                                                  <object class=\""
  "GtkCellRendererText\" id=\"renderer4\"/>\n                             "
  "                     <attributes>\n                                    "
  "                <attribute name=\"text\">0</attribute>\n               "
  "                                   </attributes>\n                     "
  "                           </child>\n                                  "
  "            </object>\n                                              <p"
  "acking>\n                                                <property name"
  "=\"expand\">False</property>\n                                         "
  "       <property name=\"position\">3</property>\n                      "
  "                        </packing>\n                                   "
  "         </child>\n                                          </object>\n"
  "                                        </child>\n                     "
  "                   <child>\n                                          <"
  "object class=\"GtkCheckButton\" id=\"chk_menu_show_app_icons\">\n      "
  "                                      <property name=\"visible\">True</"
  "property>\n                                            <property name=\""
  "can_focus\">True</property>\n                                          "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                                            <property name=\"label\""
  " translatable=\"yes\">Show _application icons in menu</property>\n     "
  "                                       <property name=\"use_underline\""
  ">True</property>\n                                            <property"
  " name=\"active\">True</property>\n                                     "
  "       <property name=\"draw_indicator\">True</property>\n             "
  "                             </object>\n                               "
  "           <packing>\n                                            <prop"
  "erty name=\"position\">1</property>\n                                  "
  "        </packing>\n                                        </child>\n "
  "                                       <child>\n                       "
  "                   <object class=\"GtkHBox\" id=\"hbox12\">\n          "
  "                                  <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                                    "
  "        <property name=\"spacing\">12</property>\n                     "
  "                       <child>\n                                       "
  "       <object class=\"GtkButton\" id=\"button5\">\n                   "
  "                             <property name=\"visible\">True</property>"
  "\n                                                <property name=\"can_"
  "focus\">True</property>\n                                              "
  "  <property name=\"receives_default\">True</property>\n                "
  "                                <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                                      "
  "          <property name=\"label\" translatable=\"yes\">_Edit desktop m"
  "enu</property>\n                                                <proper"
  "ty name=\"use_underline\">True</property>\n                            "
  "                  </object>\n                                          "
  "    <packing>\n                                                <propert"
  "y name=\"expand\">False</property>\n                                   "
  "           </packing>\n                                            </ch"
  "ild>\n                                          </object>\n            "
  "                              <packing>\n                              "
  "              <property name=\"position\">2</property>\n               "
  "                           </packing>\n                                "
  "        </child>\n                                      </object>\n    "
  "                                </child>\n                             "
  "     </object>\n                                  <packing>\n          "
  "                          <property name=\"position\">1</property>\n   "
  "                               </packing>\n                            "
  "    </child>\n                              </object>\n                "
  "            </child>\n                          </object>\n            "
  "            </child>\n                        <child type=\"label\">\n "
  "                         <object class=\"GtkLabel\" id=\"label10\">\n  "
  "                          <property name=\"visible\">True</property>\n "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                            <property name="
  "\"label\" translatable=\"yes\">&lt;b&gt;Desktop Menu&lt;/b&gt;</propert"
  "y>\n                            <property name=\"use_markup\">True</pro"
  "perty>\n                          </object>\n                        </"
  "child>\n                      </object>\n                      <packing"
  ">\n                        <property name=\"expand\">False</property>\n"
  "                      </packing>\n                    </child>\n       "
  "             <child>\n                      <object class=\"GtkFrame\" "
  "id=\"frame5\">\n                        <property name=\"visible\">True"
  "</property>\n                        <property name=\"events\">GDK_POIN"
  "TER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK "
  "| GDK_BUTTON_RELEASE_MASK</property>\n                        <property"
  " name=\"label_xalign\">0</property>\n                        <property "
  "name=\"shadow_type\">GTK_SHADOW_NONE</property>\n                      "
  "  <child>\n                          <object class=\"GtkAlignment\" id="
  "\"alignment6\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "    <property name=\"border_width\">6</property>\n                     "
  "       <property name=\"left_padding\">6</property>\n                  "
  "          <child>\n                              <object class=\"GtkVBo"
  "x\" id=\"vbox8\">\n                                <property name=\"vis"
  "ible\">True</property>\n                                <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "                  <property name=\"spacing\">6</property>\n            "
  "                    <child>\n                                  <object "
  "class=\"GtkCheckButton\" id=\"chk_show_winlist_menu\">\n               "
  "                     <property name=\"visible\">True</property>\n      "
  "                              <property name=\"can_focus\">True</proper"
  "ty>\n                                    <property name=\"events\">GDK_"
  "POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_M"
  "ASK | GDK_BUTTON_RELEASE_MASK</property>\n                             "
  "       <property name=\"label\" translatable=\"yes\">Show _window list "
  "menu on desktop middle click</property>\n                              "
  "      <property name=\"use_underline\">True</property>\n               "
  "                     <property name=\"active\">True</property>\n       "
  "                             <property name=\"draw_indicator\">True</pr"
  "operty>\n                                  </object>\n                 "
  "               </child>\n                                <child>\n     "
  "                             <object class=\"GtkAlignment\" id=\"box_wi"
  "nlist_subopts\">\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                             <property name=\"bottom_padding\">6</prope"
  "rty>\n                                    <property name=\"left_padding"
  "\">12</property>\n                                    <child>\n        "
  "                              <object class=\"GtkVBox\" id=\"vbox11\">\n"
  "                                        <property name=\"visible\">True"
  "</property>\n                                        <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "                       <property name=\"spacing\">6</property>\n       "
  "                                 <child>\n                             "
  "             <object class=\"GtkHBox\" id=\"hbox14\">\n                "
  "                            <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n                                          "
  "  <property name=\"spacing\">12</property>\n                           "
  "                 <child>\n                                             "
  " <object class=\"GtkLabel\" id=\"label23\">\n                          "
  "                      <property name=\"visible\">True</property>\n     "
  "                                           <property name=\"events\">GD"
  "K_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS"
  "_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                           "
  "                     <property name=\"label\" translatable=\"yes\">B_ut"
  "ton:</property>\n                                                <prope"
  "rty name=\"use_underline\">True</property>\n                           "
  "                     <property name=\"mnemonic_widget\">combobox8</prop"
  "erty>\n                                              </object>\n       "
  "                                       <packing>\n                     "
  "                           <property name=\"expand\">False</property>\n"
  "                                              </packing>\n             "
  "                               </child>\n                              "
  "              <child>\n                                              <o"
  "bject class=\"GtkComboBox\" id=\"combobox8\">\n                        "
  "                        <property name=\"visible\">True</property>\n   "
  "                                             <property name=\"events\">"
  "GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRE"
  "SS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                         "
  "                       <property name=\"model\">model5</property>\n    "
  "                                            <child>\n                  "
  "                                <object class=\"GtkCellRendererText\" i"
  "d=\"renderer5\"/>\n                                                  <a"
  "ttributes>\n                                                    <attrib"
  "ute name=\"text\">0</attribute>\n                                      "
  "            </attributes>\n                                            "
  "    </child>\n                                              </object>\n"
  "                                              <packing>\n              "
  "                                  <property name=\"expand\">False</prop"
  "erty>\n                                                <property name=\""
  "position\">1</property>\n                                              "
  "</packing>\n                                            </child>\n     "
  "                                       <child>\n                       "
  "                       <object class=\"GtkLabel\" id=\"label24\">\n    "
  "                                            <property name=\"visible\">"
  "True</property>\n                                                <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n     "
  "                                           <property name=\"label\" tra"
  "nslatable=\"yes\">Modi_fier:</property>\n                              "
  "                  <property name=\"use_underline\">True</property>\n   "
  "                                             <property name=\"mnemonic_"
  "widget\">combobox9</property>\n                                        "
  "      </object>\n                                              <packing"
  ">\n                                                <property name=\"exp"
  "and\">False</property>\n                                               "
  " <property name=\"position\">2</property>\n                            "
  "                  </packing>\n                                         "
  "   </child>\n                                            <child>\n     "
  "                                         <object class=\"GtkComboBox\" "
  "id=\"combobox9\">\n                                                <pro"
  "perty name=\"visible\">True</property>\n                               "
  "                 <property name=\"events\">GDK_POINTER_MOTION_MASK | GD"
  "K_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE"
  "_MASK</property>\n                                                <prop"
  "erty name=\"model\">model6</property>\n                                "
  "                <child>\n                                              "
  "    <object class=\"GtkCellRendererText\" id=\"renderer6\"/>\n         "
  "                                         <attributes>\n                "
  "                                    <attribute name=\"text\">0</attribu"
  "te>\n                                                  </attributes>\n "
  "                                               </child>\n              "
  "                                </object>\n                            "
  "                  <packing>\n                                          "
  "      <property name=\"expand\">False</property>\n                     "
  "                           <property name=\"position\">3</property>\n  "
  "                                            </packing>\n               "
  "                             </child>\n                                "
  "          </object>\n                                        </child>\n"
  "                                        <child>\n                      "
  "                    <object class=\"GtkCheckButton\" id=\"chk_winlist_s"
  "how_app_icons\">\n                                            <property"
  " name=\"visible\">True</property>\n                                    "
  "        <property name=\"can_focus\">True</property>\n                 "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                                           "
  " <property name=\"label\" translatable=\"yes\">Sh_ow application icons "
  "in menu</property>\n                                            <proper"
  "ty name=\"use_underline\">True</property>\n                            "
  "                <property name=\"active\">True</property>\n            "
  "                                <property name=\"draw_indicator\">True<"
  "/property>\n                                          </object>\n      "
  "                                    <packing>\n                        "
  "                    <property name=\"position\">1</property>\n         "
  "                                 </packing>\n                          "
  "              </child>\n                                        <child>"
  "\n                                          <object class=\"GtkCheckBut"
  "ton\" id=\"chk_show_winlist_ws_names\">\n                              "
  "              <property name=\"visible\">True</property>\n             "
  "                               <property name=\"can_focus\">True</prope"
  "rty>\n                                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "                        <property name=\"label\" translatable=\"yes\">S"
  "how workspace _names in list</property>\n                              "
  "              <property name=\"use_underline\">True</property>\n       "
  "                                     <property name=\"active\">True</pr"
  "operty>\n                                            <property name=\"d"
  "raw_indicator\">True</property>\n                                      "
  "    </object>\n                                          <packing>\n   "
  "                                         <property name=\"position\">2<"
  "/property>\n                                          </packing>\n     "
  "                                   </child>\n                          "
  "              <child>\n                                          <objec"
  "t class=\"GtkAlignment\" id=\"box_winlist_names_subopts\">\n           "
  "                                 <property name=\"visible\">True</prope"
  "rty>\n                                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "                        <property name=\"left_padding\">12</property>\n"
  "                                            <child>\n                  "
  "                            <object class=\"GtkCheckButton\" id=\"chk_s"
  "how_winlist_ws_submenus\">\n                                           "
  "     <property name=\"visible\">True</property>\n                      "
  "                          <property name=\"can_focus\">True</property>\n"
  "                                                <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "                          <property name=\"label\" translatable=\"yes\""
  ">Use _submenus for the windows in each workspace</property>\n          "
  "                                      <property name=\"use_underline\">"
  "True</property>\n                                                <prope"
  "rty name=\"draw_indicator\">True</property>\n                          "
  "                    </object>\n                                        "
  "    </child>\n                                          </object>\n    "
  "                                      <packing>\n                      "
  "                      <property name=\"position\">3</property>\n       "
  "                                   </packing>\n                        "
  "                </child>\n                                        <chil"
  "d>\n                                          <object class=\"GtkCheckB"
  "utton\" id=\"chk_show_winlist_sticky_once\">\n                         "
  "                   <property name=\"visible\">True</property>\n        "
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                            <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                            <property name=\"label\" translatable=\"yes"
  "\">Show s_ticky windows only in active workspace</property>\n          "
  "                                  <property name=\"use_underline\">True"
  "</property>\n                                            <property name"
  "=\"draw_indicator\">True</property>\n                                  "
  "        </object>\n                                          <packing>\n"
  "                                            <property name=\"position\""
  ">4</property>\n                                          </packing>\n  "
  "                                      </child>\n                       "
  "               </object>\n                                    </child>\n"
  "                                  </object>\n                          "
  "        <packing>\n                                    <property name=\""
  "position\">1</property>\n                                  </packing>\n"
  "                                </child>\n                             "
  " </object>\n                            </child>\n                     "
  "     </object>\n                        </child>\n                     "
  "   <child type=\"label\">\n                          <object class=\"Gt"
  "kLabel\" id=\"label11\">\n                            <property name=\""
  "visible\">True</property>\n                            <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "            <property name=\"label\" translatable=\"yes\">&lt;b&gt;Wind"
  "ow List Menu&lt;/b&gt;</property>\n                            <propert"
  "y name=\"use_markup\">True</property>\n                          </obje"
  "ct>\n                        </child>\n                      </object>\n"
  "                      <packing>\n                        <property name"
  "=\"expand\">False</property>\n                        <property name=\""
  "position\">1</property>\n                      </packing>\n            "
  "        </child>\n                  </object>\n                </child>"
  "\n                <child type=\"tab\">\n                  <object class"
  "=\"GtkLabel\" id=\"label2\">\n                    <property name=\"visi"
  "ble\">True</property>\n                    <property name=\"events\">GD"
  "K_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS"
  "_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    <proper"
  "ty name=\"label\" translatable=\"yes\">_Menus</property>\n             "
  "       <property name=\"use_underline\">True</property>\n              "
  "    </object>\n                  <packing>\n                    <proper"
  "ty name=\"position\">1</property>\n                    <property name=\""
  "tab_fill\">False</property>\n                  </packing>\n            "
  "    </child>\n                <child>\n                  <object class="
  "\"GtkVBox\" id=\"vbox9\">\n                    <property name=\"visible"
  "\">True</property>\n                    <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                    <property "
  "name=\"border_width\">12</property>\n                    <property name"
  "=\"spacing\">6</property>\n                    <child>\n               "
  "       <object class=\"GtkFrame\" id=\"frame6\">\n                     "
  "   <property name=\"visible\">True</property>\n                        "
  "<property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_"
  "HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                        <property name=\"label_xalign\">0</property>\n "
  "                       <property name=\"shadow_type\">GTK_SHADOW_NONE</"
  "property>\n                        <child>\n                          <"
  "object class=\"GtkAlignment\" id=\"alignment11\">\n                    "
  "        <property name=\"visible\">True</property>\n                   "
  "         <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTE"
  "R_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</p"
  "roperty>\n                            <property name=\"border_width\">6"
  "</property>\n                            <property name=\"left_padding\""
  ">6</property>\n                            <child>\n                   "
  "           <object class=\"GtkVBox\" id=\"vbox6\">\n                   "
  "             <property name=\"visible\">True</property>\n              "
  "                  <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n                                <property name=\"spa"
  "cing\">6</property>\n                                <child>\n         "
  "                         <object class=\"GtkHBox\" id=\"hbox7\">\n     "
  "                               <property name=\"visible\">True</propert"
  "y>\n                                    <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "      <property name=\"spacing\">12</property>\n                       "
  "             <child>\n                                      <object cla"
  "ss=\"GtkLabel\" id=\"label12\">\n                                      "
  "  <property name=\"visible\">True</property>\n                         "
  "               <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_"
  "POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_M"
  "ASK</property>\n                                        <property name="
  "\"label\" translatable=\"yes\">Icon _type:</property>\n                "
  "                        <property name=\"use_underline\">True</property"
  ">\n                                      </object>\n                   "
  "                   <packing>\n                                        <"
  "property name=\"expand\">False</property>\n                            "
  "          </packing>\n                                    </child>\n   "
  "                                 <child>\n                             "
  "         <object class=\"GtkComboBox\" id=\"combo_icons\">\n           "
  "                             <property name=\"visible\">True</property>"
  "\n                                        <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                            "
  "            <property name=\"model\">model7</property>\n               "
  "                         <child>\n                                     "
  "     <object class=\"GtkCellRendererText\" id=\"renderer7\"/>\n        "
  "                                  <attributes>\n                       "
  "                     <attribute name=\"text\">0</attribute>\n          "
  "                                </attributes>\n                        "
  "                </child>\n                                      </objec"
  "t>\n                                      <packing>\n                  "
  "                      <property name=\"expand\">False</property>\n     "
  "                                   <property name=\"position\">1</prope"
  "rty>\n                                      </packing>\n               "
  "                     </child>\n                                  </obje"
  "ct>\n                                  <packing>\n                     "
  "               <property name=\"expand\">False</property>\n            "
  "                      </packing>\n                                </chi"
  "ld>\n                                <child>\n                         "
  "         <object class=\"GtkHBox\" id=\"hbox8\">\n                     "
  "               <property name=\"visible\">True</property>\n            "
  "                        <property name=\"events\">GDK_POINTER_MOTION_MA"
  "SK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_"
  "RELEASE_MASK</property>\n                                    <property "
  "name=\"spacing\">12</property>\n                                    <ch"
  "ild>\n                                      <object class=\"GtkLabel\" "
  "id=\"label13\">\n                                        <property name"
  "=\"visible\">True</property>\n                                        <"
  "property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_H"
  "INT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                                        <property name=\"label\" transl"
  "atable=\"yes\">Icon _size:</property>\n                                "
  "        <property name=\"use_underline\">True</property>\n             "
  "                         </object>\n                                   "
  "   <packing>\n                                        <property name=\""
  "expand\">False</property>\n                                      </pack"
  "ing>\n                                    </child>\n                   "
  "                 <child>\n                                      <object"
  " class=\"GtkSpinButton\" id=\"spin_icon_size\">\n                      "
  "                  <property name=\"visible\">True</property>\n         "
  "                               <property name=\"can_focus\">True</prope"
  "rty>\n                                        <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                <property name=\"adjustment\">adjustment3</property>\n "
  "                                     </object>\n                       "
  "               <packing>\n                                        <prop"
  "erty name=\"expand\">False</property>\n                                "
  "        <property name=\"position\">1</property>\n                     "
  "                 </packing>\n                                    </chil"
  "d>\n                                  </object>\n                      "
  "            <packing>\n                                    <property na"
  "me=\"expand\">False</property>\n                                    <pr"
  "operty name=\"position\">1</property>\n                                "
  "  </packing>\n                                </child>\n               "
  "                 <child>\n                                      <object"
  " class=\"GtkCheckButton\" id=\"chk_show_thumbnails\">\n                "
  "                        <property name=\"visible\">True</property>\n   "
  "                                     <property name=\"can_focus\">True<"
  "/property>\n                                        <property name=\"ev"
  "ents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUT"
  "TON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                  "
  "                      <property name=\"label\" translatable=\"yes\">Sho"
  "w t_humbnails</property>\n                                        <prop"
  "erty name=\"tooltip-text\" translatable=\"yes\">Select this option to d"
  "isplay preview-able files on the desktop as automatically generated thu"
  "mbnail icons.</property>\n                                        <prop"
  "erty name=\"use_underline\">True</property>\n                          "
  "              <property name=\"draw_indicator\">True</property>\n      "
  "                                </object>\n                            "
  "    </child>\n                                <child>\n                "
  "                  <object class=\"GtkCheckButton\" id=\"chk_single_clic"
  "k\">\n                                    <property name=\"visible\">Tr"
  "ue</property>\n                                    <property name=\"can"
  "_focus\">True</property>\n                                    <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                            <property name=\"label\" translatable=\"yes"
  "\">Single _click to activate items</property>\n                        "
  "            <property name=\"use_underline\">True</property>\n         "
  "                           <property name=\"draw_indicator\">True</prop"
  "erty>\n                                  </object>\n                   "
  "             </child>\n                                <child>\n       "
  "                           <object class=\"GtkHBox\" id=\"hbox9\">\n   "
  "                                 <property name=\"visible\">True</prope"
  "rty>\n                                    <property name=\"events\">GDK"
  "_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_"
  "MASK | GDK_BUTTON_RELEASE_MASK</property>\n                            "
  "        <property name=\"spacing\">4</property>\n                      "
  "              <child>\n                                      <object cl"
  "ass=\"GtkCheckButton\" id=\"chk_custom_font_size\">\n                  "
  "                      <property name=\"visible\">True</property>\n     "
  "                                   <property name=\"can_focus\">True</p"
  "roperty>\n                                        <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "                    <property name=\"label\" translatable=\"yes\">Use c"
  "ustom _font size:</property>\n                                        <"
  "property name=\"use_underline\">True</property>\n                      "
  "                  <property name=\"draw_indicator\">True</property>\n  "
  "                                    </object>\n                        "
  "              <packing>\n                                        <prope"
  "rty name=\"expand\">False</property>\n                                 "
  "     </packing>\n                                    </child>\n        "
  "                            <child>\n                                  "
  "    <object class=\"GtkSpinButton\" id=\"spin_font_size\">\n           "
  "                             <property name=\"visible\">True</property>"
  "\n                                        <property name=\"sensitive\">"
  "False</property>\n                                        <property nam"
  "e=\"can_focus\">True</property>\n                                      "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                                        <property name=\"adjustment\""
  ">adjustment4</property>\n                                      </object"
  ">\n                                      <packing>\n                   "
  "                     <property name=\"expand\">False</property>\n      "
  "                                  <property name=\"position\">1</proper"
  "ty>\n                                      </packing>\n                "
  "                    </child>\n                                  </objec"
  "t>\n                                  <packing>\n                      "
  "              <property name=\"expand\">False</property>\n             "
  "                       <property name=\"position\">2</property>\n      "
  "                            </packing>\n                               "
  " </child>\n                                <child>\n                   "
  "               <object class=\"GtkHBox\" id=\"hbox10\">\n              "
  "                      <property name=\"events\">GDK_POINTER_MOTION_MASK"
  " | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RE"
  "LEASE_MASK</property>\n                                    <property na"
  "me=\"spacing\">12</property>\n                                    <chil"
  "d>\n                                      <object class=\"GtkLabel\" id"
  "=\"label16\">\n                                        <property name=\""
  "visible\">True</property>\n                                        <pro"
  "perty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT"
  "_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n   "
  "                                     <property name=\"label\" translata"
  "ble=\"yes\">Label trans_parency:</property>\n                          "
  "              <property name=\"use_underline\">True</property>\n       "
  "                               </object>\n                             "
  "         <packing>\n                                        <property n"
  "ame=\"expand\">False</property>\n                                      "
  "</packing>\n                                    </child>\n             "
  "                       <child>\n                                      <"
  "object class=\"GtkHScale\" id=\"hscale3\">\n                           "
  "             <property name=\"visible\">True</property>\n              "
  "                          <property name=\"can_focus\">True</property>\n"
  "                                        <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "          <property name=\"tooltip-text\" translatable=\"yes\">Specify "
  "the transparency level for the rounded label drawn behind the icon text"
  "</property>\n                                        <property name=\"a"
  "djustment\">adjustment5</property>\n                                   "
  "     <property name=\"digits\">0</property>\n                          "
  "              <property name=\"value_pos\">GTK_POS_RIGHT</property>\n  "
  "                                    </object>\n                        "
  "              <packing>\n                                        <prope"
  "rty name=\"position\">1</property>\n                                   "
  "   </packing>\n                                    </child>\n          "
  "                        </object>\n                                  <p"
  "acking>\n                                    <property name=\"position\""
  ">3</property>\n                                  </packing>\n          "
  "                      </child>\n                              </object>"
  "\n                            </child>\n                          </obj"
  "ect>\n                        </child>\n                        <child "
  "type=\"label\">\n                          <object class=\"GtkLabel\" i"
  "d=\"label14\">\n                            <property name=\"visible\">"
  "True</property>\n                            <property name=\"events\">"
  "GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRE"
  "SS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                         "
  "   <property name=\"label\" translatable=\"yes\">&lt;b&gt;Appearance&lt"
  ";/b&gt;</property>\n                            <property name=\"use_ma"
  "rkup\">True</property>\n                          </object>\n          "
  "              </child>\n                      </object>\n              "
  "        <packing>\n                        <property name=\"expand\">Fa"
  "lse</property>\n                      </packing>\n                    <"
  "/child>\n                    <child>\n                      <object cla"
  "ss=\"GtkFrame\" id=\"frame7\">\n                        <property name="
  "\"visible\">True</property>\n                        <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "       <property name=\"label_xalign\">0</property>\n                  "
  "      <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n      "
  "                  <child>\n                          <object class=\"Gt"
  "kAlignment\" id=\"alignment12\">\n                            <property"
  " name=\"visible\">True</property>\n                            <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                     <property name=\"border_width\">6</property>\n    "
  "                        <property name=\"left_padding\">6</property>\n "
  "                           <child>\n                              <obje"
  "ct class=\"GtkScrolledWindow\" id=\"scrolledwindow2\">\n               "
  "                 <property name=\"visible\">True</property>\n          "
  "                      <property name=\"can_focus\">True</property>\n   "
  "                             <property name=\"events\">GDK_POINTER_MOTI"
  "ON_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BU"
  "TTON_RELEASE_MASK</property>\n                                <property"
  " name=\"hscrollbar_policy\">GTK_POLICY_AUTOMATIC</property>\n          "
  "                      <property name=\"vscrollbar_policy\">GTK_POLICY_A"
  "UTOMATIC</property>\n                                <property name=\"s"
  "hadow_type\">GTK_SHADOW_ETCHED_IN</property>\n                         "
  "       <child>\n                                  <object class=\"GtkTr"
  "eeView\" id=\"treeview_default_icons\">\n                              "
  "      <property name=\"visible\">True</property>\n                     "
  "               <property name=\"can_focus\">True</property>\n          "
  "                          <property name=\"events\">GDK_POINTER_MOTION_"
  "MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTO"
  "N_RELEASE_MASK</property>\n                                    <propert"
  "y name=\"headers_visible\">False</property>\n                          "
  "        </object>\n                                </child>\n          "
  "                    </object>\n                            </child>\n  "
  "                        </object>\n                        </child>\n  "
  "                      <child type=\"label\">\n                         "
  " <object class=\"GtkLabel\" id=\"label15\">\n                          "
  "  <property name=\"visible\">True</property>\n                         "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n                            <property name=\"label\" translatable=\""
  "yes\">&lt;b&gt;Default Icons&lt;/b&gt;</property>\n                    "
  "        <property name=\"use_markup\">True</property>\n                "
  "          </object>\n                        </child>\n                "
  "      </object>\n                      <packing>\n                     "
  "   <property name=\"position\">1</property>\n                      </pa"
  "cking>\n                    </child>\n                  </object>\n    "
  "            </child>\n                <child type=\"tab\">\n           "
  "       <object class=\"GtkLabel\" id=\"label3\">\n                    <"
  "property name=\"visible\">True</property>\n                    <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "             <property name=\"label\" translatable=\"yes\">_Icons</prop"
  "erty>\n                    <property name=\"use_underline\">True</prope"
  "rty>\n                  </object>\n                  <packing>\n       "
  "             <property name=\"position\">2</property>\n                "
  "    <property name=\"tab_fill\">False</property>\n                  </p"
  "acking>\n                </child>\n              </object>\n           "
  " </child>\n          </object>\n          <packing>\n            <prope"
  "rty name=\"position\">1</property>\n          </packing>\n        </chi"
  "ld>\n        <child internal-child=\"action_area\">\n          <object "
  "class=\"GtkHButtonBox\" id=\"dialog-action_area1\">\n            <prope"
  "rty name=\"visible\">True</property>\n            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            <child>\n"
  "              <object class=\"GtkButton\" id=\"button2\">\n            "
  "    <property name=\"visible\">True</property>\n                <proper"
  "ty name=\"can_focus\">True</property>\n                <property name=\""
  "receives_default\">True</property>\n                <property name=\"ev"
  "ents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUT"
  "TON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <p"
  "roperty name=\"label\">gtk-help</property>\n                <property n"
  "ame=\"use_stock\">True</property>\n              </object>\n           "
  " </child>\n            <child>\n              <object class=\"GtkButton"
  "\" id=\"button1\">\n                <property name=\"visible\">True</pr"
  "operty>\n                <property name=\"can_focus\">True</property>\n"
  "                <property name=\"receives_default\">True</property>\n  "
  "              <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_P"
  "OINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MA"
  "SK</property>\n                <property name=\"label\">gtk-close</prop"
  "erty>\n                <property name=\"use_stock\">True</property>\n  "
  "            </object>\n              <packing>\n                <proper"
  "ty name=\"position\">1</property>\n              </packing>\n          "
  "  </child>\n          </object>\n          <packing>\n            <prop"
  "erty name=\"expand\">False</property>\n            <property name=\"pac"
  "k_type\">GTK_PACK_END</property>\n          </packing>\n        </child"
  ">\n      </object>\n    </child>\n    <action-widgets>\n      <action-w"
  "idget response=\"-11\">button2</action-widget>\n      <action-widget re"
  "sponse=\"-3\">button1</action-widget>\n    </action-widgets>\n  </objec"
  "t>\n</interface>\n"
};

static const unsigned xfdesktop_settings_ui_length = 58342u;

