#!/bin/bash
#
# The wrapper script to switch off UTF-8 locale and Turkish locale
# as it borks on many places

if [ "x$1" = 'x-x' ]; then
    shift
else
    echo >&2 "WARNING: Forcing to use C locale as DDD borks on UTF-8 and/or TR locale"
    echo >&2 "         Use -x switch to override"
    export LC_ALL=C
fi

exec -a ddd /usr/bin/ddd.bin "$@"

