--- amsn-0.98.4.orig/Makefile.in	2010-12-29 23:12:57.664000249 +0200
+++ amsn-0.98.4/Makefile.in	2010-12-30 09:27:29.669000248 +0200
@@ -8,11 +8,11 @@
 
 STATIC		:= @STATIC@
 
-doc_files	:= docs INSTALL CREDITS FAQ GNUGPL HELP README TODO AGREEMENT remote.help
+doc_files	:= INSTALL CREDITS FAQ GNUGPL HELP README TODO AGREEMENT remote.help
 
 FILES_TO_INSTALL := *.tcl hotmlog.htm amsn amsn-remote amsn-remote-CLI amsn.desktop langlist
 FILES_TO_INSTALL += $(doc_files)
-FILES_TO_INSTALL += desktop-icons lang skins utils/des utils/base64 utils/drawboard utils/framec utils/http
+FILES_TO_INSTALL += lang skins utils/des utils/base64 utils/drawboard utils/framec utils/http
 FILES_TO_INSTALL += utils/pixmapscroll utils/pixmapmenu utils/contentmanager
 FILES_TO_INSTALL += utils/scalable-bg utils/sha1 utils/snit utils/BWidget-1.9.0 utils/dpbrowser
 FILES_TO_INSTALL += plugins utils/sexytile
@@ -223,7 +223,7 @@
 	mkdir -p $(DESTDIR)$(dstdir)/$(PACKAGE)
 	mkdir -p $(DESTDIR)$(slnkdir)
 	mkdir -p $(DESTDIR)$(dstdir)/applications/
-	mkdir -p $(DESTDIR)$(dstdir)/pixmaps/
+	mkdir -p $(DESTDIR)$(dstdir)/icons/hicolor/
 
 	@for p in $?; do \
 		mkdir -p `dirname $(DESTDIR)$(dstdir)/$(PACKAGE)/$$p`;\
@@ -240,7 +240,7 @@
 
 	cp $(srcdir)/amsn.desktop $(DESTDIR)$(dstdir)/applications/
 
-	ln -sf $(dstdir)/$(PACKAGE)/desktop-icons/48x48/apps/amsn.png $(DESTDIR)$(dstdir)/pixmaps/
+	cp -Rf $(srcdir)/desktop-icons/* $(DESTDIR)$(dstdir)/icons/hicolor/
 
 uninstall::
 	rm -Rf $(dstdir)/$(PACKAGE)
@@ -248,7 +248,6 @@
 	rm -f $(slnkdir)/amsn-remote
 	rm -f $(slnkdir)/amsn-remote-CLI
 	rm -f $(dstdir)/applications/amsn.desktop
-	rm -f $(dstdir)/pixmaps/amsn.png
 
 rpm: all
 	mkdir -p ./distrib
