#!/bin/sh

# fix for users of special IM modules
unset XMODIFIERS GTK_IM_MODULE QT_IM_MODULE

LD_LIBRARY_PATH="/opt/sun-jre/lib/i386/:/opt/sun-jre/lib/amd64/" exec java -Xmx1024M -Xms512M -cp /usr/share/minecraft/minecraft.jar net.minecraft.LauncherFrame $@
