/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_xfdesktop_thunar_proxy
#define DBUS_GLIB_CLIENT_WRAPPERS_xfdesktop_thunar_proxy

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
xfdesktop_thunar_proxy_bulk_rename (DBusGProxy *proxy, const char * IN_working_directory, const char ** IN_filenames, const gboolean IN_standalone, const char * IN_display, const char * IN_startup_id, GError **error)

{
  return dbus_g_proxy_call (proxy, "BulkRename", error, G_TYPE_STRING, IN_working_directory, G_TYPE_STRV, IN_filenames, G_TYPE_BOOLEAN, IN_standalone, G_TYPE_STRING, IN_display, G_TYPE_STRING, IN_startup_id, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*xfdesktop_thunar_proxy_bulk_rename_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
xfdesktop_thunar_proxy_bulk_rename_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(xfdesktop_thunar_proxy_bulk_rename_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
xfdesktop_thunar_proxy_bulk_rename_async (DBusGProxy *proxy, const char * IN_working_directory, const char ** IN_filenames, const gboolean IN_standalone, const char * IN_display, const char * IN_startup_id, xfdesktop_thunar_proxy_bulk_rename_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "BulkRename", xfdesktop_thunar_proxy_bulk_rename_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_working_directory, G_TYPE_STRV, IN_filenames, G_TYPE_BOOLEAN, IN_standalone, G_TYPE_STRING, IN_display, G_TYPE_STRING, IN_startup_id, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
xfdesktop_thunar_proxy_terminate (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "Terminate", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*xfdesktop_thunar_proxy_terminate_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
xfdesktop_thunar_proxy_terminate_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(xfdesktop_thunar_proxy_terminate_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
xfdesktop_thunar_proxy_terminate_async (DBusGProxy *proxy, xfdesktop_thunar_proxy_terminate_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Terminate", xfdesktop_thunar_proxy_terminate_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_xfdesktop_thunar_proxy */

G_END_DECLS
