#!/bin/bash

. "${PM_FUNCTIONS}"

command_exists /sbin/pccardctl || exit $NA

case "$1" in
    hibernate|suspend)
        echo "ejecting PCMCIA cards..."
        /sbin/pccardctl eject
        ;;
    thaw|resume)
        echo "inserting PCMCIA cards..."
        /sbin/pccardctl insert
        ;;
    *) exit $NA
        ;;
esac


exit 0
