#!/bin/bash
# The ndiswrapper hook - relead the ndiswrapper module

. "${PM_FUNCTIONS}"

command_exists /usr/sbin/ndiswrapper || return $NA

case "$1" in
    resume|thaw)
        modprobe -r ndiswrapper
        modprobe ndiswrapper
        ;;
    *) exit $NA
        ;;
esac
