--- smile/smile.pro.orig	2010-03-14 13:52:48.500918288 +0200
+++ smile/smile.pro	2010-03-14 13:53:06.954870022 +0200
@@ -15,6 +15,7 @@
 	       smile_pl.ts \
 	       smile_ru.ts \
 	       smile_pt.ts \
+	       smile_tr.ts \
 	       smile_es.ts
 
 # Input
