--- cmt/src/makefile.org	2007-11-23 23:40:18.000000000 +0200
+++ cmt/src/makefile	2007-11-24 02:11:05.000000000 +0200
@@ -11,8 +11,9 @@
 # GENERAL
 #
 
-CFLAGS		=	$(INCLUDES) -Wall -O3 -fPIC
-CXXFLAGS	=	$(CFLAGS)
+#CFLAGS		=	$(INCLUDES) -Wall  -fPIC
+#CXXFLAGS =  $(INCLUDES) -Wall -fPIC
+#	=	$(CFLAGS)
 PLUGIN_LIB	=	../plugins/cmt.so
 
 ###############################################################################
@@ -74,28 +75,28 @@
 	-strip $(PLUGIN_LIB)
 	cp $(PLUGIN_LIB) $(INSTALL_PLUGINS_DIR)
 
-test:	/tmp/test.wav ../../ladspa_sdk/snd/noise.wav always
-	@echo ---------------------------------------------
-	@echo First listen to the white noise input signal:
-	@echo ---------------------------------------------
-	play ../../ladspa_sdk/snd/noise.wav
-	@echo -------------------------
-	@echo Compare to plugin output.
-	@echo -------------------------
-	@echo Should be a noise band around 6000Hz, repeated quietly after 1s.
-	play /tmp/test.wav
-
-/tmp/test.wav:	$(PLUGIN_LIB) ../../ladspa_sdk/snd/noise.wav
-	analyseplugin $(PLUGIN_LIB)
-	echo;analyseplugin -l $(PLUGIN_LIB);echo
-	time applyplugin	-s 1					\
-				../../ladspa_sdk/snd/noise.wav		\
-				/tmp/test.wav				\
-				$(PLUGIN_LIB) lpf 500			\
-				$(PLUGIN_LIB) lpf 500			\
-				$(PLUGIN_LIB) sine_fcaa 6000		\
-				$(PLUGIN_LIB) delay_5s 1 0.1		\
-				$(PLUGIN_LIB) amp_mono 4		\
+#test:	/tmp/test.wav ../../ladspa_sdk/snd/noise.wav always
+#	@echo ---------------------------------------------
+#	@echo First listen to the white noise input signal:
+#	@echo ---------------------------------------------
+#	play ../../ladspa_sdk/snd/noise.wav
+#	@echo -------------------------
+#	@echo Compare to plugin output.
+#	@echo -------------------------
+#	@echo Should be a noise band around 6000Hz, repeated quietly after 1s.
+#	play /tmp/test.wav
+
+#/tmp/test.wav:	$(PLUGIN_LIB) ../../ladspa_sdk/snd/noise.wav
+#	analyseplugin $(PLUGIN_LIB)
+#	echo;analyseplugin -l $(PLUGIN_LIB);echo
+#	time applyplugin	-s 1					\
+#				../../ladspa_sdk/snd/noise.wav		\
+#				/tmp/test.wav				\
+#				$(PLUGIN_LIB) lpf 500			\
+#				$(PLUGIN_LIB) lpf 500			\
+#				$(PLUGIN_LIB) sine_fcaa 6000		\
+#				$(PLUGIN_LIB) delay_5s 1 0.1		\
+#				$(PLUGIN_LIB) amp_mono 4		\
 
 ###############################################################################
 #
