#! /bin/sh
#
# The startup wrapper for ImageJ

if [ -z "${JAVA_HOME}" ] ; then
	JAVA_HOME=/usr/lib/jvm/java-7-openjdk
fi

JAVA_BIN=${JAVA_HOME}/bin/java

if [ ! -x ${JAVA_BIN} ] ; then
	echo "Failed to find executable '${JAVA_BIN}'" > /dev/stderr
	exit -1
fi

IMAGEJ_JAR=/usr/share/java/ij.jar
IMAGEJ_RUN="${JAVA_BIN} -Dplugins.dir=/usr/share/ImageJ/plugins -jar ${IMAGEJ_JAR}"

if [ ! -f ${IMAGEJ_JAR} ] ; then
   echo "Failed to find library '${IMAGEJ_JAR}'" > /dev/stderr
   exit -1
fi

${IMAGEJ_RUN} $@ 
