diff -Nur libmpeg3-1.7-old/audio/Makefile.am libmpeg3-1.7/audio/Makefile.am
--- libmpeg3-1.7-old/audio/Makefile.am	1970-01-01 02:00:00.000000000 +0200
+++ libmpeg3-1.7/audio/Makefile.am	2006-09-28 20:12:31.000000000 +0300
@@ -0,0 +1,12 @@
+noinst_LTLIBRARIES = libmpeg3_audio.la
+libmpeg3_audio_la_SOURCES = ac3.c dct.c huffman.c layer2.c layer3.c mpeg3audio.c pcm.c synthesizers.c tables.c 
+libmpeg3_audio_la_LDFLAGS =
+
+AM_CFLAGS = $(CPU_CFLAGS) $(LARGEFILE_CFLAGS)
+AM_CXXFLAGS = $(CPU_CFLAGS) $(LARGEFILE_CFLAGS)
+INCLUDES=-I$(srcdir)/..
+
+pkgincludedir=$(includedir)/libmpeg3/audio
+pkginclude_HEADERS=ac3.h huffman.h mpeg3audio.h tables.h
+LIBTOOL = $(SHELL) $(top_builddir)/libtool $(LTC_FLAGS)
+
diff -Nur libmpeg3-1.7-old/configure.ac libmpeg3-1.7/configure.ac
--- libmpeg3-1.7-old/configure.ac	1970-01-01 02:00:00.000000000 +0200
+++ libmpeg3-1.7/configure.ac	2006-09-27 23:54:29.000000000 +0300
@@ -0,0 +1,62 @@
+dnl Process this file with autoconf to produce a configure script.
+
+AC_PREREQ(2.59)
+
+AC_INIT([libmpeg3], [1.7], [mail])
+
+
+AM_INIT_AUTOMAKE(libmpeg3, 1.7)
+
+AC_LANG_C
+AC_PROG_CC
+
+
+
+AC_ENABLE_SHARED
+AC_DISABLE_STATIC
+AC_PROG_LIBTOOL
+AM_PROG_AS
+
+
+enable_mmx=no
+
+AC_ARG_ENABLE(mmx, AC_HELP_STRING([--enable-mmx], [enables support for mmx (default is disabled)]), [ enable_mmx=$enableval ], [ enable_mmx=no ])
+
+if test "x$enable_mmx" = "xyes"; then
+	CPU_CFLAGS="-DHAVE_MMX -DUSE_MMX $CPU_CFLAGS" # -D_MMX_ doesn't work
+	have_asm_mmx=true
+fi
+
+AM_CONDITIONAL(USEMMX, test "x$enable_mmx" = "xyes")
+
+
+############## A52DEC
+AC_CHECK_LIB(a52,a52_init,[liba52=yes])
+AC_CHECK_HEADER(a52dec/a52.h,[liba52h=yes])
+
+if test "x$liba52$liba52h" = "xyesyes"; then
+	A52DEC_CFLAGS=
+	A52DEC_LIBS=-la52
+fi
+AC_SUBST(A52DEC_CFLAGS)
+AC_SUBST(A52DEC_LDFLAGS)
+############## END OF A52DEC
+
+############# CSS SUPPORT IN LIBMPEG3
+AC_ARG_ENABLE(css, 
+							AC_HELP_STRING([--disable-css], [disable support for css in libmpeg3 (default=enabled)]),,
+							[ enable_css=$enableval ],
+							[ enable_css=yes ])
+if test "x$enable_css" = "xyes"; then
+	CSS_CFLAGS="-DHAVE_CSS"
+fi
+AC_SUBST(CSS_CFLAGS)
+############## END OF CSS SUPPORT IN LIBMPEG3
+
+
+LARGEFILE_CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64"
+AC_SUBST(LARGEFILE_CFLAGS)
+
+
+AC_CONFIG_FILES([Makefile audio/Makefile video/Makefile])
+AC_OUTPUT
diff -Nur libmpeg3-1.7-old/Makefile.am libmpeg3-1.7/Makefile.am
--- libmpeg3-1.7-old/Makefile.am	1970-01-01 02:00:00.000000000 +0200
+++ libmpeg3-1.7/Makefile.am	2006-09-28 20:12:25.000000000 +0300
@@ -0,0 +1,30 @@
+SUBDIRS = audio video 
+
+lib_LTLIBRARIES = libmpeg3.la
+AM_CFLAGS = $(CPU_CFLAGS) $(LARGEFILE_CFLAGS) $(CSS_CFLAGS)
+libmpeg3_la_LDFLAGS = -version-info 1:0:0 -release 1.7.0 -Wl,--no-undefined
+libmpeg3_la_LIBADD = -la52 video/libmpeg3_video.la audio/libmpeg3_audio.la -lm \
+		     -lpthread
+libmpeg3_la_SOURCES = bitstream.c libmpeg3.c mpeg3atrack.c mpeg3css.c \
+	mpeg3demux.c \
+	mpeg3ifo.c \
+	mpeg3io.c \
+	mpeg3strack.c \
+	mpeg3title.c \
+	mpeg3tocutil.c \
+											mpeg3vtrack.c workarounds.c 
+bin_PROGRAMS = mpeg3dump mpeg3toc mpeg3cat mpeg3peek mpeg3split
+mpeg3dump_SOURCES = mpeg3dump.c
+mpeg3dump_LDADD = libmpeg3.la
+mpeg3toc_SOURCES = mpeg3toc.c
+mpeg3toc_LDADD = libmpeg3.la
+mpeg3cat_SOURCES = mpeg3cat.c
+mpeg3cat_LDADD = libmpeg3.la
+mpeg3peek_SOURCES = mpeg3peek.c
+mpeg3peek_LDADD = libmpeg3.la
+mpeg3split_SOURCES = mpeg3split.c
+mpeg3split_LDADD = libmpeg3.la
+
+pkgincludedir=$(includedir)/libmpeg3
+pkginclude_HEADERS=libmpeg3.h mpeg3private.h bitstream.h ifo.h mpeg3atrack.h mpeg3css.h mpeg3demux.h  mpeg3io.h mpeg3private.inc mpeg3protos.h mpeg3title.h mpeg3vtrack.h timecode.h workarounds.h
+LIBTOOL = $(SHELL) $(top_builddir)/libtool $(LTC_FLAGS)
diff -Nur libmpeg3-1.7-old/video/Makefile.am libmpeg3-1.7/video/Makefile.am
--- libmpeg3-1.7-old/video/Makefile.am	1970-01-01 02:00:00.000000000 +0200
+++ libmpeg3-1.7/video/Makefile.am	2006-09-28 20:12:38.000000000 +0300
@@ -0,0 +1,28 @@
+noinst_LTLIBRARIES = libmpeg3_video.la
+libmpeg3_video_la_SOURCES = getpicture.c \
+			    headers.c \
+			    idct.c \
+			    macroblocks.c \
+			    mmxtest.c \
+			    motion.c \
+			    mpeg3cache.c \
+			    mpeg3video.c \
+			    output.c \
+			    reconstruct.c \
+			    seek.c \
+			    slice.c \
+			    subtitle.c \
+			    vlc.c
+libmpeg3_video_la_LDFLAGS=
+
+if USEMMX
+libmpeg3_video_la_SOURCES += mmxidct.S reconmmx.s
+endif
+
+AM_CFLAGS = $(CPU_CFLAGS) $(LARGEFILE_CFLAGS)
+INCLUDES=-I$(srcdir)/..
+
+pkgincludedir=$(includedir)/libmpeg3/video
+pkginclude_HEADERS=idct.h layerdata.h mpeg3video.h mpeg3videoprotos.h slice.h vlc.h
+
+LIBTOOL = $(SHELL) $(top_builddir)/libtool $(LTC_FLAGS)
