#!/bin/sh

# stop this script if the local blender path is a symlink
 if [ -L \${HOME}/.blender ]; then
echo "Detected a symbolic link for \${HOME}/.blender"
echo "Sorry, to avoid dangerous situations, the Blender binary can"
echo "not be started until	you have removed the symbolic link:"
echo "  # rm -i \${HOME}/.blender"
exit 1
fi

export BLENDER_SYSTEM_SCRIPTS="/usr/share/blender/scripts"
export BLENDER_SYSTEM_DATAFILES="/usr/share/blender/${VERSION}/datafiles"

exec blender-bin "$@"
