
 Force usage of our Makefile

sed -i '/all:/s:$:\n\t./config.status --file debian/extra/Makefile\n\t$(MAKE) -C debian/extra $@:' Makefile.in


diff -Nur jpeg-8b-old/Makefile.in jpeg-8b/Makefile.in
--- jpeg-8b-old/Makefile.in	2010-08-16 15:46:30.310000994 +0300
+++ jpeg-8b/Makefile.in	2010-08-16 15:46:32.308000941 +0300
@@ -391,6 +391,8 @@
         testoutt.jpg
 
 all: jconfig.h
+	./config.status --file debian/extra/Makefile
+	$(MAKE) -C debian/extra $@
 	$(MAKE) $(AM_MAKEFLAGS) all-am
 
 .SUFFIXES:
@@ -936,9 +938,13 @@
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: install-am
+	./config.status --file debian/extra/Makefile
+	$(MAKE) -C debian/extra $@
 install-exec: install-exec-am
 install-data: install-data-am
 uninstall: uninstall-am
+	./config.status --file debian/extra/Makefile
+	$(MAKE) -C debian/extra $@
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
