--- Makefile.orig	2009-02-23 10:36:59.000000000 +0200
+++ Makefile	2009-02-23 10:39:57.000000000 +0200
@@ -67,21 +67,21 @@
 # Add -DNO_MALLOC_DECL if your system does not like the malloc() declaration
 # in detex.l (reported by pinard@iro.umontreal.ca)
 #
-#DEFS	+= ${DEFS} -DNO_MALLOC_DECL
+DEFS += -DNO_MALLOC_DECL
 #
-CFLAGS	= -O ${DEFS}
+CFLAGS= -0  ${DEFS}
 
 # Use your favorite lexical scanner
 #
-LEX	= lex
-#LEX	= flex
+#LEX	= lex
+LEX	= flex
 
 #LFLAGS	= -8 -C
 
 # scanner library
 #
-LEXLIB	= -ll
-#LEXLIB	= -lfl
+#LEXLIB	= -ll
+LEXLIB	= -lfl
 
 LPR	= lpr -p
 
