#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import comar

def setState(if_name, state):
    link = comar.Link()

    if state == "up":
        for package in link.Network.Link:
            for connection in link.Network.Link[package].connections():
                info = link.Network.Link[package].connectionInfo(connection)
                if info["device_id"].split("_")[-1] == if_name and info.get("state", "down") == "unplugged":
                    link.Network.Link[package].setState(connection, "up")
    elif state == "down":
        for package in link.Network.Link:
            for connection in link.Network.Link[package].connections():
                info = link.Network.Link[package].connectionInfo(connection)
                if info["device_id"].split("_")[-1] == if_name and info.get("state", "") not in ["down", "inaccessible"]:
                    link.Network.Link[package].setState(connection, "unplugged")

    return 0

def printUsage():
    print "Usage: %s iface up/down" % sys.argv[0]

def main():
    try:
        prog, if_name, state = sys.argv
    except ValueError:
        printUsage()
        return 1

    if state not in ["up", "down"]:
        printUsage()
        return 1

    return setState(if_name, state)

if __name__ == '__main__':
    sys.exit(main())
