#!/bin/bash
#
# Will move all the patches which don't apply into the
# PATCHES_BROKEN_DIR.
#
# usage: kcooker-rebase < kernel-quilt-tree >
#
# Luiz Fernando N. Capitulino
# <lcapitulino@mandriva.com.br>

KERNEL_TREE=$1
PATCHES_BROKEN_DIR=../../PATCHES/patches-broken/
SERIES_FILE=patches/series

push_all()
{
	quilt next
	if [ $? -eq 1 ]; then
		return 0
	fi

	quilt push -aq
	return 1
}

move_broken()
{
	file=""
	patch=""

	file=$(quilt next)
	patch=$(basename $file)

	svn mv $file $PATCHES_BROKEN_DIR
	sed -i s/${patch}/"# BROKEN: ${patch}"/g $SERIES_FILE
}

cd $KERNEL_TREE

while true; do
	push_all
	if [ $? -eq 0 ]; then
		exit 0
	fi
	move_broken
done
