#!/bin/bash

# Copyright (C) 2002, 2003 by MandrakeSoft,
# Juan Quintela <quintela@mandrakesoft.com>, 
# Redistribution of this file is permitted under the terms of the GNU 
# Public License (GPL)

VERSION=0.2

usage () {
    echo "usage: `basename $0` [--version] [-v]  [--configs_dir=<configs_dir>]" >&2
    echo -e "\t(ex: `basename $0`" >&2
    exit 1
}

# Globals

# verbose messages
configs_dir=""
verbose=0

print () {
	[  $verbose -eq 0 ] && return
	echo -e "$1"
}

# looking for options

while [ $# -gt 0 ]; do
	case $1 in
		-v|--verborse)
			verbose=1
		    	;;
		--version)
			echo "`basename $0`: version $VERSION"
			exit 0
			;;
	        --configs_dir=*)
		        configs_dir=`echo $1 | sed -e 's/--configs_dir=//'`
			;;
		*) 	
			usage
			;;
	esac
	shift
done

if [ -z "$configs_dir" ]; then
	configs_dir=`dirname $0`/../configs
fi

if [ ! -d "$configs_dir" ]; then
	echo "$configs_dir is not a directory"
	exit 2
fi

print "configs dir is: $configs_dir"

for i in $configs_dir/*.config; do
	if [ -f $i ]; then
		# - thing to also work for kernel-linus
		architecture="`basename $i .config | cut -d'-' -f2`"
		print dealing with arch $architecture
		install -m 644 $i $i.old
		install -m 644 $i .config
		make ARCH=$architecture oldconfig
		if [ $? -ne 0 ]; then
			printf "\nmake oldconfig for $i failed\n\n"
			exit 1
		fi
		install -m 644  .config $i
	else
		echo "file $i don't exist"
		exit 3
	fi
done

exit 0
