Index: src/Makefile
===================================================================
--- src/Makefile.orig
+++ src/Makefile
@@ -8,9 +8,6 @@
 # Version:	@(#)Makefile  2.85-13  23-Mar-2004  miquels@cistron.nl
 #
 
-CC	= gcc
-CFLAGS	= -ansi -W -Wall -O2 -fomit-frame-pointer -D_GNU_SOURCE
-LDFLAGS	= -s
 STATIC	=
 
 # For some known distributions we do not build all programs, otherwise we do.
@@ -49,6 +53,7 @@ BIN_COMBO	= $(BIN_OWNER):$(BIN_GROUP)
 STRIP		= strip -s -R .comment
 INSTALL_EXEC	= install -o $(BIN_OWNER) -g $(BIN_GROUP) -m 755
 INSTALL_DATA	= install -o $(BIN_OWNER) -g $(BIN_GROUP) -m 644
+INSTALL_DIR 	= install -d
 MANDIR		= /usr/share/man
 
 ifeq ($(WITH_SELINUX),yes)
@@ -127,6 +132,9 @@ clobber:	cleanobjs
 distclean:	clobber
 
 install:
+		$(INSTALL_DIR) -d $(ROOT)/bin $(ROOT)/sbin $(ROOT)/usr/bin \
+			$(ROOT)/usr/include $(ROOT)/$(MANDIR)/man1 $(ROOT)/$(MANDIR)/man5 \
+			$(ROOT)/$(MANDIR)/man8
 		for i in $(BIN); do \
 			$(STRIP) $$i ; \
 			$(INSTALL_EXEC) $$i $(ROOT)/bin/ ; \
