--- a/Makefile	2009-03-19 12:19:57.000000000 +0200
+++ b/Makefile	2009-03-19 12:21:08.000000000 +0200
@@ -3,8 +3,8 @@
 #
 
 # Compiler settings
-CC      = gcc
-CFLAGS  = -O2 -fPIC -Wall -ansi -pedantic
+CC      = ${CC}
+CFLAGS  = ${CFLAGS}
 
 # Ar settings to build the library
 AR	    = ar
@@ -12,7 +12,7 @@
 
 SHLD = ${CC} ${CFLAGS}
 LDSHFLAGS = -shared -Wl,-Bsymbolic  -Wl,-rpath -Wl,/usr/lib -Wl,-rpath,/usr/lib
-LDFLAGS = -Wl,-rpath -Wl,/usr/lib -Wl,-rpath,/usr/lib
+LDFLAGS = ${LDFLAGS}
 
 # Set RANLIB to ranlib on systems that require it (Sun OS < 4, Mac OSX)
 # RANLIB  = ranlib
