--- Makefile.standalone.orig	2009-05-10 21:04:36.931367743 +0300
+++ Makefile.standalone	2009-05-10 21:04:52.554367922 +0300
@@ -11,7 +11,7 @@
 
 driver:
 	$(MAKE) -C $(KSRC) SUBDIRS=$(PWD) modules
-	@ctags -R
+
 
 clean:
 	$(MAKE) -C $(KSRC) SUBDIRS=$(PWD) clean
