Index: foo2zjs/Makefile
===================================================================
--- foo2zjs.orig/Makefile
+++ foo2zjs/Makefile
@@ -1028,6 +1028,7 @@ install-hotplug-osx:
 
 install-filter:
 	if [ "$(CUPS_SERVERBIN)" != "" ]; then \
+        mkdir -p $(CUPS_SERVERBIN)/filter/; \
 	    ln -sf $(BIN)/command2foo2lava-pjl $(CUPS_SERVERBIN)/filter/; \
 	fi
 
