.TH CLUSTALW 1 "2003 July 1" "Manual for clustalw"
.SH NAME
clustalw \- a multiple sequence alignment program

.SH SYNOPSIS
.B clustalw
.I "[options]"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR clustalx
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has other documentation; see below.
.PP
.B clustalx
is a windows interface for the ClustalW multiple sequence alignment
program. It provides an integrated environment for performing multiple sequence
and profile alignments and analysing the results. The sequence alignment is
displayed in a window on the screen. A versatile coloring scheme has been
incorporated allowing you to highlight conserved features  in the alignment.
The pull-down menus at the top of the window allow you to select all the
options required for traditional multiple sequence and profile alignment.
.P
You can cut-and-paste sequences to change the order of the alignment; you can
select a subset of sequences to be aligned; you can select a sub-range of the
alignment to be realigned and inserted back into the original alignment.
.P
Alignment quality analysis can be performed and low-scoring segments or
exceptional residues can be highlighted.

.SH "SEE ALSO"
Files in /usr/share/doc/clustalx contain a lot
of details. The Web page <http://www.clustal.org/>
is also helpful.
.SH AUTHOR
This manual page was written by Andreas Tille <tille@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

