Index: chkconfig-1.3.47/Makefile
===================================================================
--- chkconfig-1.3.47.orig/Makefile
+++ chkconfig-1.3.47/Makefile
@@ -1,13 +1,11 @@
 VERSION=$(shell awk '/Version:/ { print $$2 }' chkconfig.spec)
 TAG = chkconfig-$(VERSION)
 
-CFLAGS=-g -Wall $(RPM_OPT_FLAGS) -D_GNU_SOURCE
-LDFLAGS=-g
-MAN=chkconfig.8 ntsysv.8 alternatives.8
+MAN=alternatives.8
 PROG=chkconfig
 BINDIR = /sbin
 SBINDIR = /usr/sbin
-MANDIR = /usr/man
+MANDIR = /usr/share/man
 ALTDIR = /var/lib/alternatives
 ALTDATADIR = /etc/alternatives
 SUBDIRS = po
@@ -15,7 +13,7 @@ SUBDIRS = po
 OBJS=chkconfig.o leveldb.o
 NTOBJS=ntsysv.o leveldb.o
 
-all: subdirs $(PROG) ntsysv alternatives
+all: subdirs alternatives
 
 subdirs:
 	for d in $(SUBDIRS); do \
@@ -49,16 +47,12 @@ clean:
 	rm -f chkconfig-*.tar.gz *~ *.old
 
 install:
-	[ -d $(DESTDIR)/$(BINDIR) ] || mkdir -p $(DESTDIR)/$(BINDIR)
 	[ -d $(DESTDIR)/$(SBINDIR) ] || mkdir -p $(DESTDIR)/$(SBINDIR)
 	[ -d $(DESTDIR)/$(MANDIR) ] || mkdir -p $(DESTDIR)/$(MANDIR)
 	[ -d $(DESTDIR)/$(MANDIR)/man8 ] || mkdir -p $(DESTDIR)/$(MANDIR)/man8
-	[ -d $(DESTDIR)/$(MANDIR)/man5 ] || mkdir -p $(DESTDIR)/$(MANDIR)/man5
 	[ -d $(DESTDIR)/$(ALTDIR) ] || mkdir -p -m 755 $(DESTDIR)/$(ALTDIR)
 	[ -d $(DESTDIR)/$(ALTDATADIR) ] || mkdir -p -m 755 $(DESTDIR)/$(ALTDATADIR)
 
-	install -m 755 $(PROG) $(DESTDIR)/$(BINDIR)/$(PROG)
-	install -m 755 ntsysv $(DESTDIR)/$(SBINDIR)/ntsysv
 	install -m 755 alternatives $(DESTDIR)/$(SBINDIR)/alternatives
 	ln -s alternatives $(DESTDIR)/$(SBINDIR)/update-alternatives
 	
