--- test/Makefile.am.orig	2010-02-09 14:16:14.000000000 +0200
+++ test/Makefile.am	2013-03-13 18:25:59.822645828 +0200
@@ -65,7 +65,7 @@
 	test-async-cancel \
 	test-escape       \
 	test-uri       	  \
-	$(srcdir)/auto-test	
+	$(top_srcdir)auto-test	
 
 libraries =						\
 	$(top_builddir)/libgnomevfs/libgnomevfs-2.la	\
