#!/bin/bash

# Skype does not work well with newer version of GSPCA Webcams driver
# (Linux Kernel >=2.6.27), possible workaround.
# http://share.skype.com/sites/garage/2010/01/skype_21_beta_2_aka_talking_sc.html

if [ -x /usr/bin/skype.bin ]; then
    LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so /usr/bin/skype.bin
else
    LD_PRELOAD=/usr/lib32/libv4l/v4l1compat.so /usr/bin/32/skype.bin
fi
