#!/bin/zsh
#
#command not found handler for zsh.
#This handler is part of Zsh and is hooked to command-not-found program.
#man zshmisc is your friend.

function command_not_found_handler()
{
    /usr/bin/python /usr/bin/command-not-found $1;
    return $?
}
