Index: system-config-nfs-1.3.51/Makefile
===================================================================
--- system-config-nfs-1.3.51.orig/Makefile
+++ system-config-nfs-1.3.51/Makefile
@@ -35,8 +35,6 @@ install: all
 	mkdir -p $(DESTDIR)/$(BINDIR)
 	mkdir -p $(DESTDIR)/$(PKGDATADIR)
 	mkdir -p $(DESTDIR)/$(PKGIMAGEDIR)
-	mkdir -p $(DESTDIR)/$(PAMD_DIR)
-	mkdir -p $(DESTDIR)/$(SECURITY_DIR)
 	mkdir -p $(DESTDIR)/$(DATADIR)/applications
 	mkdir -p $(DESTDIR)/$(DATADIR)/icons/hicolor/48x48/apps
 	install -m 0644 src/$(PKGNAME).glade $(DESTDIR)$(PKGDATADIR)
@@ -45,12 +43,10 @@ install: all
 	for py in src/*.py ; do \
 		sed -e s,@VERSION@,$(VERSION),g $${py} > $(DESTDIR)$(PKGDATADIR)/`basename $${py}` ; \
 	done
-	install -m 0644 $(PKGNAME).pam $(DESTDIR)/$(PAMD_DIR)/$(PKGNAME)
-	install -m 0644 $(PKGNAME).console $(DESTDIR)/$(SECURITY_DIR)/$(PKGNAME)
 	install -m 0644 pixmaps/*.png $(DESTDIR)/$(PKGIMAGEDIR)
 	install -m 0644 pixmaps/${PKGNAME}.png $(DESTDIR)/$(DATADIR)/icons/hicolor/48x48/apps
 	install -m 0644 ${PKGNAME}.desktop $(DESTDIR)/$(DATADIR)/applications/${PKGNAME}.desktop
-	ln -sf consolehelper $(DESTDIR)/$(BINDIR)/$(PKGNAME)
+	ln -sf $(PKGDATADIR)/system-config-nfs.py $(DESTDIR)/$(BINDIR)/$(PKGNAME)
 	for d in $(SUBDIRS); do \
 	(cd $$d; $(MAKE) DESTDIR=$(DESTDIR) MANDIR=$(MANDIR) install) \
 		|| case "$(MFLAGS)" in *k*) fail=yes;; *) exit 1;; esac; \
