#!/bin/sh

UCLIBC_PREFIX="/usr/lib/uClibc"

export C_INCLUDE_PATH="$UCLIBC_PREFIX/usr/include:$(gcc -print-search-dirs|grep install:|cut -d\  -f2)/include"
export LD_RUN_PATH="$UCLIBC_PREFIX/lib"
export LIBRARY_PATH="$LD_RUN_PATH:$UCLIBC_PREFIX/usr/lib"
export GCC_EXEC_PREFIX="$LD_RUN_PATH"

exec gcc -Wl,--dynamic-linker,$UCLIBC_PREFIX/lib/ld-uClibc.so.0 $@
