--- Makefile	2007-05-31 23:21:49.000000000 +0300
+++ Makefile	2007-05-31 23:22:19.000000000 +0300
@@ -120,18 +120,18 @@
 # Installation-related stuff
 # 
 # The base dir for installation and subdirs in it
-INSTDIR = /usr/local
+INSTDIR = /usr
 # for binaries
 BINDIR = $(INSTDIR)/bin
 # for binaries of little general interest
 LIBXDIR = $(INSTDIR)/lib/ttf2pt1
 # for scripts, maps/encodings etc.
 SHAREDIR = $(INSTDIR)/share/ttf2pt1
-MANDIR = $(INSTDIR)/man
+MANDIR = $(INSTDIR)/share/man
 
 # owner and group of installed files
 OWNER = root
-GROUP = bin
+GROUP = root
 
 # After you have configured the Makefile, comment out the following
 # definition:
