#!/bin/bash

MAIN="funnyboat"
DATADIR="/usr/share/$MAIN"
TARGET="$HOME/.$MAIN"
TOSYMLINK="data `ls $DATADIR|grep "\.py$"`"

if [ ! -e "$TARGET" ]; then
	mkdir "$TARGET"
fi
for d in $TOSYMLINK; do
	if [ ! -e "$TARGET/$d" ] ; then
		ln -s "$DATADIR/$d" "$TARGET/$d"
	fi
done

cd "$TARGET"
exec python main.py "$@"
