diff -Naur gdpc-2.2.5.orig/Makefile gdpc-2.2.5/Makefile
--- gdpc-2.2.5.orig/Makefile	2009-07-10 13:00:14.000000000 +0300
+++ gdpc-2.2.5/Makefile	2010-01-29 11:19:08.598252340 +0200
@@ -1,4 +1,3 @@
-CC = gcc
 FLAGS=$(CFLAGS) -g -Wall `pkg-config --cflags gtk+-2.0 gthread-2.0` -DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED -DGDK_PIXBUF_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED
 LIBS=`pkg-config --libs gtk+-2.0 gthread-2.0`
 bindir ?= /usr/bin
@@ -7,7 +6,7 @@
 	$(CC) -c $(FLAGS) $(CPPFLAGS) $<
 
 gdpc: main.o colors.o sort.o drawatoms.o readinput.o init.o rotate.o setup.o Makefile
-	$(CC) $(CFLAGS) -o gdpc main.o colors.o drawatoms.o init.o sort.o rotate.o setup.o readinput.o $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o gdpc main.o colors.o drawatoms.o init.o sort.o rotate.o setup.o readinput.o $(LIBS)
 
 main.o: main.c parameters.h
 
@@ -29,7 +28,7 @@
 	rm *.o gdpc
 
 install:
-	install -p -m 755 -D gdpc $(bindir)/gdpc
+	install -p -m 755 -D gdpc $(DESTDIR)$(bindir)/gdpc
 
 uninstall:
 	rm $(bindir)/gdpc
