#!/bin/sh
#
# A wrapper for mplayer -identify to easily get info of a file
#

if [ -z "$1" ]; then
    echo "Usage: midentify <file> [<file> ...]"
    exit 1
fi

mplayer -vo null -ao null -frames 0 -identify "$@" 2>/dev/null |
    grep IDENTIFY |
    sed -n -e 's/.*ID_/ID_/' -e 's/[]()|&;<>`'"'"'\\!$" []/\\&/g;p'

