#!/bin/bash

# Skype does not work well with newer version of GSPCA Webcams driver
# (Linux Kernel >=2.6.27), possible workaround.
# http://share.skype.com/sites/garage/2010/01/skype_21_beta_2_aka_talking_sc.html

if [ -x /usr/bin/skype.bin ]; then
    export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/lib/libv4l/v4l1compat.so"
    PULSE_LATENCY_MSEC=30 exec "/usr/bin/skype.bin" "$@"
else
    export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/lib32/libv4l/v4l1compat.so"
    PULSE_LATENCY_MSEC=30 exec "/usr/bin/32/skype.bin" "$@"
fi
