Index: utils/Makefile
===================================================================
--- utils/Makefile.orig
+++ utils/Makefile
@@ -4,7 +4,7 @@ usrsbindir = /usr/sbin
 DRIVER_DIR ?= ../driver
 
 CC = gcc
-CFLAGS = -g -Wall -I$(DRIVER_DIR)
+CFLAGS += -I$(DRIVER_DIR)
 
 DISTFILES=Makefile ndiswrapper loadndisdriver.c ndiswrapper-buginfo
 
Index: Makefile
===================================================================
--- Makefile.orig
+++ Makefile
@@ -9,13 +9,9 @@ DISTFILES=AUTHORS ChangeLog INSTALL Make
 				   ndiswrapper.8 loadndisdriver.8
 SUBDIRS = utils driver
 
-ifeq ($(wildcard /usr/share/man)$(wildcard /usr/man),/usr/man)
-mandir = /usr/man
-else
 mandir = /usr/share/man
-endif
 
-KVERS ?= $(shell uname -r)
+KVERS ?=
 
 .PHONY: all
 all: $(SUBDIRS)
Index: driver/Makefile
===================================================================
--- driver/Makefile.orig
+++ driver/Makefile
@@ -12,7 +12,7 @@ DISTFILES = \
 # By default, we try to compile the modules for the currently running
 # kernel.  But it's the first approximation, as we will re-read the
 # version from the kernel sources.
-KVERS ?= $(shell uname -r)
+KVERS ?=
 
 # KBUILD is the path to the Linux kernel build tree.  It is usually the
 # same as the kernel source tree, except when the kernel was compiled in
@@ -36,13 +36,7 @@ ifeq (,$(wildcard $(VERSION_H)))
 $(error Cannot find kernel version in $(KBUILD), is it configured?)
 endif
 
-KVERS := $(shell sed -ne 's/"//g;s/^\#define UTS_RELEASE //p' $(VERSION_H))
-
-ifeq (,$(KVERS))
-$(error Cannot find UTS_RELEASE in $(VERSION_H), has 'make modules_prepare' been called?)
-endif
-
-INST_DIR = /lib/modules/$(KVERS)/misc
+INST_DIR = /lib/modules/$(KVERS)/updates
 
 SRC_DIR=$(shell pwd)
 
@@ -196,9 +190,6 @@ install: config_check $(MODULE)
 		{ echo "$(MODULE)" is not for Linux $(KVERS); exit 1; }
 	mkdir -p -m 755 $(DESTDIR)$(INST_DIR)
 	install -m 0644 $(MODULE) $(DESTDIR)$(INST_DIR)
-ifndef DESTDIR
-	-/sbin/depmod -a $(KVERS)
-endif
 
 uninstall:
 	rm -f $(DESTDIR)$(INST_DIR)/$(MODULE)
