'\" t
.\"     Title: pkaction
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: May 2009
.\"    Manual: pkaction
.\"    Source: polkit
.\"  Language: English
.\"
.TH "PKACTION" "1" "May 2009" "polkit" "pkaction"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pkaction \- Get details about a registered action
.SH "SYNOPSIS"
.HP \w'\fBpkaction\fR\ 'u
\fBpkaction\fR [\fB\-\-version\fR] [\fB\-\-help\fR]
.HP \w'\fBpkaction\fR\ 'u
\fBpkaction\fR [\fB\-\-verbose\fR]
.HP \w'\fBpkaction\fR\ 'u
\fBpkaction\fR \fB\-\-action\-id\fR\ \fIaction\fR [\fB\-\-verbose\fR]
.SH "DESCRIPTION"
.PP

\fBpkaction\fR
is used to obtain information about registered PolicyKit actions\&. If called with
\fB\-\-action\-id\fR
then all actions are displayed\&. Otherwise the action
\fIaction\fR\&. If called without the
\fB\-\-verbose\fR
option only the name of the action is shown\&. Otherwise details about the actions are shown\&.
.SH "RETURN VALUE"
.PP
On success
\fBpkaction\fR
returns 0\&. Otherwise a non\-zero value is returned and a diagnostic message is printed on standard error\&.
.SH "AUTHOR"
.PP
Written by David Zeuthen
davidz@redhat\&.com
with a lot of help from many others\&.
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the polkit\-devel mailing list, see the link
\m[blue]\fB\%http://lists.freedesktop.org/mailman/listinfo/polkit-devel\fR\m[]
on how to subscribe\&.
.SH "SEE ALSO"
.PP

\fBpolkit\fR(8),
\fBpkcheck\fR(1),
\fBpkexec\fR(1)
