--- src~/game/Makefile	2011-01-04 11:08:49.501546329 +0200
+++ src/game/Makefile	2011-01-04 11:26:34.298171173 +0200
@@ -33,8 +33,8 @@
 # the compiler options
 
 CC      := gcc
-INC     := -I. -I.. -I../enet/include ${SDLCONF_I} -I./extensions -I./file_formats -I./platform
-LDFLAGS := ${SDLCONF_L} -L../enet/lib -lSDL_ttf -lSDL_mixer -lGL -lGLU -lSDL_image -lphysfs -lenet
+INC     := -I. -I..  ${SDLCONF_I} -I./extensions -I./file_formats -I./platform
+LDFLAGS := ${SDLCONF_L} -lSDL_ttf -lSDL_mixer -lGL -lGLU -lSDL_image -lphysfs   -lenet
 
 # use different options if the environmental variable PREFIX is defined
 ifdef ($(PREFIX),"")
@@ -43,7 +43,7 @@
 	OPT := -Os -Wall -DPREFIX=\"${PREFIX}\" -D_NIX_PREFIX
 endif
 
-CFLAGS  := ${OPT} ${INC}
+CFLAGS  := ${OPT} ${INC} -DENET11
 
 #------------------------------------
 # definitions of the target projects
--- src/Makefile~	2011-01-04 12:32:09.996424099 +0200
+++ src/Makefile	2011-01-04 12:33:32.851303914 +0200
@@ -10,11 +10,11 @@
 endif
 
 
-PROJ_NAME := egoboo-2.x
+PROJ_NAME := egoboo
 
 .PHONY: all clean
 
-all: enet egoboo
+all: egoboo
 
 clean:
 	make -C ./enet clean
@@ -25,7 +25,7 @@
 
 enet:   ./enet/lib/libenet.a
 
-egoboo: enet
+egoboo:
 	make -C ./game all PREFIX=$(PREFIX) PROJ_NAME=$(PROJ_NAME)
 	
 egoboo_lua: enet
@@ -49,13 +49,13 @@
 	#
 
 #	copy the binary to the games folder
-	mkdir -p ${PREFIX}/games
-	install -m 755 ./game/${PROJ_NAME} ${PREFIX}/games
+	mkdir -p ${PREFIX}
+	install -m 755 ./${PROJ_NAME} ${PREFIX}/
 
 #	copy the data to the games folder
-	mkdir -p ${PREFIX}/share/games/${PROJ_NAME}
-	cp -rdf ./basicdat ${PREFIX}/share/games/${PROJ_NAME}
-	cp -rdf ./modules ${PREFIX}/share/games/${PROJ_NAME}
+	mkdir -p ${PREFIX}/share/${PROJ_NAME}
+	cp -rdf ./basicdat ${PREFIX}/share/${PROJ_NAME}
+	cp -rdf ./modules ${PREFIX}/share/${PROJ_NAME}
 
 #	copy the players to the user's data folder
 	mkdir -p ${HOME}/.${PROJ_NAME}
