Index: compat-wireless-2011-08-27-p/Makefile
===================================================================
--- compat-wireless-2011-08-27-p.orig/Makefile
+++ compat-wireless-2011-08-27-p/Makefile
@@ -92,7 +92,6 @@ btinstall: btuninstall bt-install-module
 bt-install-modules: bt
 	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) BT=TRUE \
 		modules_install
-	@/sbin/depmod -ae
 	@echo
 	@echo "Currently detected bluetooth subsystem modules:"
 	@echo
@@ -128,9 +127,6 @@ btuninstall:
 	@# New location, matches upstream
 	@rm -rf $(KLIB)/$(KMODDIR)/net/bluetooth/
 	@rm -rf $(KLIB)/$(KMODDIR)/drivers/bluetooth/
-	@# Lets only remove the stuff we are sure we are providing
-	@# on the misc directory.
-	@/sbin/depmod -ae
 	@echo
 	@echo "Your old bluetooth subsystem modules were left intact:"
 	@echo
@@ -160,12 +156,11 @@ btclean:
 	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) BT=TRUE clean
 	@rm -f $(CREL_PRE)*
 
-install: uninstall install-modules install-scripts
+install: install-modules
 
 install-modules: modules
 	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) \
 		modules_install
-	@./scripts/update-initramfs
 
 install-scripts:
 	@# All the scripts we can use
@@ -197,19 +192,8 @@ install-scripts:
 		echo Running iwl-enable iwlagn...;\
 		/usr/sbin/iwl-enable iwlagn ;\
 	fi
-	@# If on distributions like Mandriva which like to
-	@# compress their modules this will find out and do
-	@# it for you. Reason is some old version of modutils
-	@# won't know mac80211.ko should be used instead of
-	@# mac80211.ko.gz
-	@./scripts/compress_modules
-	@# Mandrake doesn't have a depmod.d/ conf file to prefer
-	@# the updates/ dir which is what we use so we add one for it
-	@# (or any other distribution that doens't have this).
-	@./scripts/check_depmod
 	@# Udev stuff needed for the new compat_firmware_class.
 	@./compat/scripts/compat_firmware_install
-	@/sbin/depmod -a
 	@echo
 	@echo "Currently detected wireless subsystem modules:"
 	@echo 
@@ -340,7 +324,6 @@ uninstall:
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/misc/eeprom/eeprom_93cx6.ko*
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/misc/eeprom_93cx6.ko*
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/net/b44.ko*
-	@/sbin/depmod -a
 	@echo
 	@echo "Your old wireless subsystem modules were left intact:"
 	@echo 
