--- /dev/null	2007-03-15 17:35:15.320405438 +0200
+++ Makefile	2007-03-15 23:47:00.000000000 +0200
@@ -0,0 +1,23 @@
+BINDIR = /usr/bin
+
+all: install
+
+install:
+	mkdir -p $(BINDIR)
+	mkdir -p $(DESTDIR)/dtds/decls
+	mkdir -p $(DESTDIR)/lib
+	mkdir -p $(DESTDIR)/common
+	mkdir -p $(DESTDIR)/html
+	mkdir -p $(DESTDIR)/print
+	mkdir -p $(DESTDIR)/images
+	install bin/collateindex.pl $(BINDIR)
+	cp catalog $(DESTDIR)
+	cp VERSION $(DESTDIR)
+	cp dtds/decls/docbook.dcl $(DESTDIR)/dtds/decls
+	cp lib/dblib.dsl $(DESTDIR)/lib
+	cp common/*.dsl $(DESTDIR)/common
+	cp common/*.ent $(DESTDIR)/common
+	cp html/*.dsl $(DESTDIR)/html
+	cp lib/*.dsl $(DESTDIR)/lib
+	cp print/*.dsl $(DESTDIR)/print
+	cp images/*.gif $(DESTDIR)/images
