#!/bin/sh

# Simple script to set regulatory domain.
# Derived by Fedora, simplified for Pardus
# 2009

# Let's define a default one
COUNTRY=US

TIMEZONERC=/etc/timezone
TIMEZONE=

if [ -f $TIMEZONERC ]
then
	# This should set TIMEZONE
	TIMEZONE=$(cat $TIMEZONERC 2>/dev/null)
else
	echo "Timezone information not found!"
fi

if [ -z "$TIMEZONE" ]
then
	echo "Timezone information not set!"
else
    COOKED_ZONE=$(echo $TIMEZONE | sed -e 's/ /_/')
    COUNTRY=$(grep $COOKED_ZONE /usr/share/zoneinfo/zone.tab | awk '{ print $1 }')
fi

if [ -z "$COUNTRY" ]
then
    COUNTRY=US
	echo "Could not determine country! Fallbacking to $COUNTRY."
fi

iw reg set $COUNTRY
