diff -ur macfanctld-orig/Makefile macfanctld/Makefile
--- macfanctld-orig/Makefile	2013-02-27 00:28:53.576785486 +0200
+++ macfanctld/Makefile	2013-02-27 15:52:13.377978520 +0200
@@ -15,16 +15,8 @@
 	$(CC) $(CFLAGS) macfanctl.c control.c config.c -o macfanctld 
 
 clean:
-	dh_testdir
-	dh_clean
 	rm -rf *.o macfanctld
 
 install:
-	dh_installdirs
 	chmod +x macfanctld
-	cp macfanctld $(SBIN_DIR)
-	cp macfanctl.conf $(ETC_DIR)
-
-uninstall:
-	rm $(SBIN_DIR)/macfanctld $(INITD_DIR)/macfanctl $(ETC_DIR)/macfanctl.conf
 
