
[[ -e "/etc/profile.env" ]] && source /etc/profile.env

umask 022

if [[ "$USER" == root ]]; then
	export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${ROOTPATH}"
else
	export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH}"
fi

unset ROOTPATH
