diff -Nur smpeg-0.4.4-old/Makefile.in smpeg-0.4.4/Makefile.in
--- smpeg-0.4.4-old/Makefile.in	2006-09-06 18:42:23.411763888 +0300
+++ smpeg-0.4.4/Makefile.in	2006-09-06 18:42:37.580609896 +0300
@@ -108,7 +108,7 @@
 libsmpeg_la_LDFLAGS =          -release $(LT_RELEASE)		-version-info $(LT_CURRENT):$(LT_REVISION):$(LT_AGE)
 
 
-libsmpeg_la_LIBADD =  	audio/libaudio.la		video/libvideo.la
+libsmpeg_la_LIBADD =  	audio/libaudio.la		video/libvideo.la -lstdc++
 
 
 EXTRA_DIST =  	CHANGES			COPYING			TODO			README			README.SDL_mixer 	plaympeg.1		gtv.1			VisualC.zip		smpeg.m4		autogen.sh
