#!/bin/bash

MAIN="AssaultCube"
DATADIR="/usr/share/$MAIN"
TARGET="$HOME/.$MAIN"
TOSYMLINK="ac_client ac_server packages/audio packages/misc packages/models packages/textures"
TOCOPY="bot config"
EMPTYDIRS="screenshots packages demos"
MAPDIR="packages/maps"

if [ ! -e "$TARGET" ]; then
	mkdir "$TARGET"
fi

for d in $EMPTYDIRS; do
	if [ -L "$TARGET/$d" ]; then
		rm -f "$TARGET/$d"
	fi
	if [ ! -e "$TARGET/$d" ]; then
		mkdir "$TARGET/$d"
	fi
done

for d in $TOSYMLINK; do
	if [ ! -e "$TARGET/$d" ] ; then
		ln -s "$DATADIR/$d" "$TARGET/$d"
	fi
done

for d in $TOCOPY; do
	if [ ! -e "$TARGET/$d" ] ; then
		f=`echo $d|sed 's/$DATADIR//'`
		cp -R "$DATADIR/$d" "$TARGET/$f"
	fi
done

if [ ! -e "$TARGET/$MAPDIR" ]; then
	mkdir "$TARGET/$MAPDIR"
fi

for f in $DATADIR/$MAPDIR/*; do
	cp -f "$f" "$TARGET/$MAPDIR/"
done

cd "$TARGET"
exec ./ac_server "$@"

