--- source/src/Makefile.orig	2010-11-14 19:46:24.000000000 +0100
+++ source/src/Makefile		2012-09-23 00:40:46.018056769 +0200
@@ -5,7 +5,7 @@ override CXXFLAGS+= -Wall -fsigned-char
 PLATFORM= $(shell uname -s)
 PLATFORM_PREFIX=native
 
-INCLUDES= -I. -Ibot -I../enet/include
+INCLUDES= -I. -Ibot
 
 STRIP=
 ifeq (,$(findstring -g,$(CXXFLAGS)))
@@ -26,7 +26,7 @@ USRLIB=$(shell if [ -e /usr/lib64 ]; the
 override CXXFLAGS+= -rdynamic
 CLIENT_INCLUDES= $(INCLUDES) -I/usr/include `sdl-config --cflags` -idirafter ../include
 # -lSDL_ttf 
-CLIENT_LIBS= -L../enet/.libs -lenet -L$(USRLIB) `sdl-config --libs` -lSDL_image -lz -lGL -lopenal -lvorbisfile
+CLIENT_LIBS= -lenet -L$(USRLIB) `sdl-config --libs` -lSDL_image -lz -lGL -lopenal -lvorbisfile -lX11
 endif
 
 CLIENT_OBJS= \
@@ -93,7 +93,7 @@ SERVER_INCLUDES= -DSTANDALONE $(INCLUDES
 SERVER_LIBS= -L../lib -lzdll -lenet -llibintl -lws2_32 -lwinmm
 else
 SERVER_INCLUDES= -DSTANDALONE $(INCLUDES)
-SERVER_LIBS= -L../enet/.libs -lenet -lz
+SERVER_LIBS= -lenet -lz
 endif
 
 SERVER_OBJS= \
@@ -121,18 +121,8 @@ default: all
 
 all: client server
 
-../enet/Makefile:
-	cd ../enet; ./configure --enable-shared=no --enable-static=yes
-
-libenet: ../enet/Makefile
-	-$(MAKE) -C ../enet all
-
-clean-enet: ../enet/Makefile
-	$(MAKE) -C ../enet/ clean
-
 clean:
 	-$(RM) $(CLIENT_PCH) $(CLIENT_OBJS) $(SERVER_OBJS) $(MASTER_OBJS) ac_client ac_server ac_master
-#	-$(MAKE) -C ../enet/ clean
 
 %.h.gch: %.h
 	$(CXX) $(CXXFLAGS) -o $@.tmp $(subst .h.gch,.h,$@)
@@ -164,13 +154,13 @@ client_install: client
 server_install: server
 
 else
-client: libenet $(CLIENT_OBJS)
+client: $(CLIENT_OBJS)
 	$(CXX) $(CXXFLAGS) -o ac_client $(CLIENT_OBJS) $(CLIENT_LIBS)
 
-server: libenet $(SERVER_OBJS)
+server: $(SERVER_OBJS)
 	$(CXX) $(CXXFLAGS) -o ac_server $(SERVER_OBJS) $(SERVER_LIBS)  
 
-master: libenet $(MASTER_OBJS)
+master: $(MASTER_OBJS)
 	$(CXX) $(CXXFLAGS) -o ac_master $(MASTER_OBJS) $(SERVER_LIBS)  
 	
 client_install: client