#!/bin/sh
# This is a stripped down version of svnlastchange

if [ $# -eq 0 ]; then
    cat <<EOF
Usage:
    svnlastlog <filename> [<filename> ...]

EOF
    exit 1
fi
echo >&2 "Warning: svnlastlog is superfluous"
echo >&2 "Use svn log -r COMMITTED"

svn log -r COMMITTED "$*"
