#!/bin/bash

GLESTDIR="/usr/share/glest"

if [ ! -d ~/.glest ]; then
    mkdir ~/.glest
fi
for d in data docs maps scenarios screens techs tilesets; do
    if [ ! -L ~/.glest/$d ] ; then
        ln -s "$GLESTDIR/$d" ~/.glest/$d
    fi
done
if [ ! -L ~/.glest/glest ] ; then
    ln -s "$GLESTDIR/lib/glest" ~/.glest/glest
fi
if [ ! -e ~/.glest/glest.ini ] ; then
    cp "$GLESTDIR/config/glest.ini" ~/.glest/glest.ini
fi
if [ ! -e ~/.glest/servers.ini ] ; then
    cp "$GLESTDIR/servers.ini" ~/.glest/servers.ini
fi
if [ ! -e ~/.glest/configuration.xml ] ; then
    cp "$GLESTDIR/configuration.xml" ~/.glest/configuration.xml
fi
if [ ! -e ~/.glest/glest.log ] ; then
    touch ~/.glest/glest.log
fi

cd ~/.glest
exec ./glest "$@"
