.TH ALSAUNMUTE 1 "21 April 2010"
.SH NAME
alsaunmute \- a simple script to initialize ALSA sound devices

.SH DESCRIPTION
\fBalsaunmute\fP is a shell script which runs the \fBalsactl(1)\fP
utility with \fIinit\fP argument (see the script for details).

.SH OPTIONS
None

.SS
Example:
\fBalsaunmute\fR

.SH SEE ALSO
\fB
alsactl(1),
alsamixer(1),
amixer(1)
\fP

.SH BUGS 
None known.

.SH AUTHOR
\fBalsaunmute\fP is by Jaroslav Kysela <perex@perex.cz>

