diff -Nur ensemblist-040126-old/Makefile ensemblist-040126/Makefile
--- ensemblist-040126-old/Makefile	2006-08-20 13:09:26.626670536 +0300
+++ ensemblist-040126/Makefile	2006-08-20 13:11:29.136046280 +0300
@@ -1,13 +1,12 @@
 NAME=ensemblist
-CC=gcc
 ifdef DEBUG
 DATADIR=/home/rixed/src/ensemblist/datas
 COMPILE_FLAGS=-Wall -fno-builtin -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wredundant-decls -O0 -g `libmikmod-config --cflags` -DDATADIR=$(DATADIR)
-LINK_FLAGS=-g -lm -L /usr/X11R6/lib -lXmu -lGL -lglut -lGLU -lpng `libmikmod-config --libs` -lefence -lpthread
+LINK_FLAGS=-g -lm -L /usr/lib -lXmu -lGL -lglut -lGLU -lpng `libmikmod-config --libs` -lefence -lpthread
 else
 DATADIR=$(DESTDIR)/usr/share/$(NAME)
-COMPILE_FLAGS=-Wall -O3 -fomit-frame-pointer `libmikmod-config --cflags` -DNDEBUG -DDATADIR=$(DATADIR)
-LINK_FLAGS=-lm -L /usr/X11R6/lib -lXmu -lGL -lglut -lGLU -lpng `libmikmod-config --libs` -lpthread
+COMPILE_FLAGS=$(CFLAGS) `libmikmod-config --cflags` -DNDEBUG -DDATADIR=$(DATADIR)
+LINK_FLAGS=-lm -L /usr/lib -lXmu -lGL -lglut -lGLU -lpng `libmikmod-config --libs` -lpthread
 endif
 APPLE_FRAMEWORKS=-framework GLUT -framework Cocoa -framework OpenGL
 #uncomment the following if you want to compile on MacOS/X
@@ -24,9 +23,6 @@
 $(NAME): $(OFILES)
 	@echo '$(COL)$@$(NORM)'
 	$(CC) $(COMPILE_FLAGS) $(LINK_FLAGS) $^ -o $@
-ifndef DEBUG
-	strip $(NAME)
-endif
 
 .c.o:
 	@echo '$(COL)$@$(NORM)'
@@ -50,8 +46,8 @@
 
 install: $(NAME)
 	@echo '$(COL)$@$(NORM)'
-	@install -d $(DATADIR) $(DESTDIR)/usr/games
-	@install -m755 $(NAME) $(DESTDIR)/usr/games
+	@install -d $(DATADIR) $(DESTDIR)/usr/bin
+	@install -m755 $(NAME) $(DESTDIR)/usr/bin
 	@find datas/ -\( -name CVS -prune -\) -o -type f -exec install -m644 \{\} $(DATADIR) \;
 
 include depends
