diff -Nur tomatoes-1.55-old/makefile tomatoes-1.55/makefile
--- tomatoes-1.55-old/makefile	2006-08-23 19:34:35.638095328 +0300
+++ tomatoes-1.55/makefile	2006-08-23 19:48:04.163180832 +0300
@@ -4,31 +4,29 @@
 
 .PHONY: all clean veryclean rebuild compress
 
-CC = g++
 COMPRESS = upx --best
 TARGET = ./tomatoes
-MARCH = pentium
 
 
 # Directory defines, you can use these defaults or adjust them if
 # necessary. Remember to include the trailing /
 
 # MPK directory (where 'tomatoes.mpk' is), default: ./
-MPKDIR = ./
+MPKDIR = /usr/share/tomatoes/
 
 # Music directory (where the music files are), default: ./music/
-MUSICDIR = ./music/
+MUSICDIR = /usr/share/tomatoes/music/
 
 # Hiscore directory (where the hiscores are written to), default: ./
 # We need read/write access!
-HISCOREDIR = ./
+HISCOREDIR = /var/lib/tomatoes/
 
 # Config directory (where the 'config.cfg' is), default: ./
 # We need read/write access!
-CONFIGDIR = ./
+CONFIGDIR = /etc/tomatoes/
 
 # Override directory (unused at the moment), default: ./data/
-OVERRIDEDIR = ./data/
+OVERRIDEDIR = /usr/share/tomatoes/data/
 
 
 DIR_DEFINES = -DLINUX -DMPK_DIR=\"$(MPKDIR)\" -DMUSIC_DIR=\"$(MUSICDIR)\" -DHISCORE_DIR=\"$(HISCOREDIR)\" -DCONFIG_DIR=\"$(CONFIGDIR)\" -DOVERRIDE_DIR=\"$(OVERRIDEDIR)\"
@@ -47,8 +45,8 @@
 CFLAGS = -MMD -g3 -O3 -march=$(MARCH) -Wall -pg
 LDFLAGS = `sdl-config --libs` -lSDL_image -lSDL_mixer -lGL -lGLU -pg
 else
-CFLAGS = -MMD -O3 -march=$(MARCH) -Wall $(SDL_FLAGS)
-LDFLAGS = `sdl-config --libs` -lSDL_image -lSDL_mixer -lGL -lGLU -s
+CFLAGS = _pardus_cflags $(SDL_FLAGS)
+LDFLAGS = `sdl-config --libs` -lSDL_image -lSDL_mixer -lGL -lGLU _pardus_ldflags
 endif
 endif
 
