--- build/gcc/Makefile.orig	2008-04-11 13:13:16.000000000 +0300
+++ build/gcc/Makefile	2008-04-11 14:36:20.000000000 +0300
@@ -31,10 +31,12 @@
 bindir = bin
 objdir = obj
 ipath=$(prefix)/bin
-CBASEFLAGS = -W -Wall -fno-rtti -fno-exceptions
+libdir=$(prefix)/lib
+CBASEFLAGS = $(CFLAGS) -W -Wall -fno-rtti -fno-exceptions
 JAVAINCS   = -I$(JAVA_HOME)/include
 CXX = g++
 INSTALL=install -o $(USER) -g $(USER)
+LN_S=ln -s 
 
 ##################################################
 
