#!/bin/sh

# Check for and abort a hibernate if the kernel indicates it has been
# updated, as we will be completly unable to resume.
if [ "$1" = "hibernate" ] && [ -f "/run/do-not-hibernate" ]; then
	echo "kernel update inhibits hibernate (/run/do-not-hibernate present)"
	exit 1
fi
